//! Persistent health store for bridges, kept next to the active config.
//!
//! Tracks every bridge we have probed, with its reachability history:
//! last successful probe, last failure-counter bump, and a `fails`
//! counter. The store drives bridge lifecycle:
//!
//! * a successful probe resets `fails` to 0 and stamps `ok`;
//! * a failed probe bumps `fails` — but at most once per `fail_window`
//!   (so a burst of retries counts once), stamping `attempt`;
//! * once `fails` reaches `max_fails`, the bridge is pruned (returned to
//!   the caller so it can also be dropped from the config).
//!
//! Failures are observed at the **probe** layer (TCP / obfs4 / webtunnel
//! reachability), which is what this process controls directly — arti
//! owns the live bridge connections and does not surface per-bridge
//! runtime failures to us.
//!
//! File format (line-based, plain text), one metadata comment per bridge:
//!
//! ```text
//! # fails=0 attempt=2026-05-14T15:00:12Z ok=2026-05-14T15:00:12Z latency=234ms
//! obfs4 1.2.3.4:80 ABCDEF... cert=... iat-mode=0
//! ```
//!
//! Dedup key: `(transport, addr, fingerprint)`.
//!
//! Shared by the CLI daemon (`apps/socks5-proxy`) and the Android JNI
//! engine (`packages/android-ffi`) — both processes probe bridges and want
//! to remember which ones tend to work across restarts.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{Context, Result};
use bridge_line::BridgeLine;
use bridge_probe::usable_for_tor;
use time::format_description::well_known::Iso8601;
use time::OffsetDateTime;

const HEADER_LINE1: &str = "# Auto-generated by tor-socks5. Bridge reachability health.";
const HEADER_LINE2_PREFIX: &str = "# Last updated at ";

type Key = (Option<String>, SocketAddr, Option<String>);

#[derive(Debug, Clone)]
struct Entry {
    bridge: BridgeLine,
    /// Last time a probe succeeded, if ever.
    last_ok: Option<OffsetDateTime>,
    /// Last time the failure counter was touched (bumped or reset). Used
    /// to rate-limit `fails` increments to once per `fail_window`.
    last_attempt: OffsetDateTime,
    /// Latency of the last successful probe.
    last_latency: Duration,
    /// Consecutive TCP-probe failure count (reset to 0 on any TCP success).
    fails: u32,
    /// Cumulative count of successful probes over the bridge's lifetime.
    /// Never reset — a long-lived, frequently-reachable bridge accrues a
    /// high count, so this is our persistent **stability** signal (used to
    /// order bridges for arti: more-proven first, then by latency).
    ok_count: u32,
    /// Number of successful PT/channel warm-ups. Unlike `ok_count`, this is
    /// recorded only after the transport channel itself accepted a connection.
    channel_ok_count: u32,
    /// Most recent successful PT/channel warm-up.
    last_channel_ok: Option<OffsetDateTime>,
    /// Number of times a full circuit through this bridge actually reached
    /// the open internet (`arti_wrapper::TorTunnel::verify_bridge_reachable`),
    /// not merely opened a channel. This is the standard the QR-scan
    /// verification flow already holds every scanned bridge to; the
    /// background watchdog applies the same check to a slow trickle of the
    /// already channel-proven pool (see `engine.rs`'s circuit-verify tick),
    /// since running it against the whole pool on every reprobe would be
    /// prohibitively expensive (see `docs/design/real-connectivity-bridge-
    /// verification.md`).
    verified_count: u32,
    /// Most recent successful end-to-end circuit verification.
    last_verified: Option<OffsetDateTime>,
    last_verification_attempt: Option<OffsetDateTime>,
    /// Consecutive **circuit-layer** failure count, observed from arti's
    /// own tracing events (per-guard usability reports). Distinct from
    /// `fails` (TCP-probe layer): a bridge whose TCP/TLS works but whose
    /// descriptor or fingerprint is stale answers reachability probes yet
    /// can't carry multi-hop circuits. Resets to 0 on a circuit success.
    circuit_fails: u32,
    /// Last time the circuit-failure counter was touched (bumped or reset).
    /// Used to rate-limit `circuit_fails` to once per
    /// `circuit_observation_window` (arti retries quickly; we mustn't
    /// count each retry as a fresh failure).
    last_circuit_observation: OffsetDateTime,
    /// Labels of the sources that offered this bridge. A line published by
    /// several collectors credits all of them, or a good source looks barren
    /// merely because another published the same line first.
    sources: std::collections::BTreeSet<String>,
}

/// `circuit_fails` value marking a bridge as permanently unusable, rather than
/// merely failing often. Written by
/// [`BridgeStore::note_permanent_failure_at`].
const RETIRED_CIRCUIT_FAILS: u32 = u32::MAX;

/// One transport's slice of the health store, for a status display.
///
/// The three counts answer progressively stronger questions, and the gaps
/// between them are the interesting part: `known` is what has been seen,
/// `alive` what answered a reachability probe, `channel_proven` what actually
/// completed a Tor channel. A transport with many alive and no channel-proven
/// bridges looks healthy and is not — the case that cost this project a day.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TransportStats {
    /// `obfs4`, `webtunnel`, or `plain` for bridges with no transport.
    pub transport: String,
    pub known: usize,
    pub alive: usize,
    pub channel_proven: usize,
    pub retired: usize,
    pub last_probe_ok: Option<OffsetDateTime>,
    pub last_channel_ok: Option<OffsetDateTime>,
}

/// What one bridge-list source has yielded, for scoring and for display.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SourceStats {
    pub label: String,
    /// Bridges this source has offered, whether or not they ever worked.
    pub offered: usize,
    /// Of those, how many answered a reachability probe.
    pub alive: usize,
    /// Of those, how many actually carried a Tor channel.
    pub channel_proven: usize,
    /// Of those, how many were retired as permanently unusable.
    pub retired: usize,
}

impl SourceStats {
    /// Whether this source has supplied enough bridges to be judged, and none
    /// of them ever worked.
    ///
    /// The sample floor matters: a source that has offered two bridges and had
    /// no luck yet is unremarkable, while one that has offered hundreds without
    /// a single reachable bridge has stopped being a source of bridges. Judged
    /// on reachability rather than on completed channels, because
    /// channel-proven counts stay at zero for any bridge the client has simply
    /// never selected.
    pub fn is_barren(&self, min_sample: usize) -> bool {
        self.offered >= min_sample && self.alive == 0
    }
}

impl Entry {
    fn is_retired(&self) -> bool {
        self.circuit_fails == RETIRED_CIRCUIT_FAILS
    }

    fn key(&self) -> Key {
        key_of(&self.bridge)
    }
}

fn key_of(b: &BridgeLine) -> Key {
    (b.transport.clone(), b.addr, b.fingerprint.clone())
}

#[derive(Debug)]
pub struct BridgeStore {
    path: PathBuf,
    entries: BTreeMap<Key, Entry>,
}

impl BridgeStore {
    /// Resolve the on-disk path of the store given the config path. When
    /// the config came from defaults we fall back to
    /// `./tor-socks5.alive-bridges.log`.
    pub fn resolve_path(config_path: Option<&Path>) -> PathBuf {
        match config_path {
            Some(cfg) => {
                let dir = cfg.parent().unwrap_or_else(|| Path::new("."));
                let stem = cfg
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_else(|| "tor-socks5".to_string());
                dir.join(format!("{stem}.alive-bridges.log"))
            }
            None => PathBuf::from("tor-socks5.alive-bridges.log"),
        }
    }

    /// Read the store from disk, silently ignoring malformed entries.
    /// Missing file → empty store.
    pub fn load(path: PathBuf) -> Result<Self> {
        let text = match fs::read_to_string(&path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                return Ok(Self {
                    path,
                    entries: BTreeMap::new(),
                });
            }
            Err(e) => return Err(e).with_context(|| format!("read {}", path.display())),
        };

        let mut entries = BTreeMap::new();
        let mut pending_meta: Option<Meta> = None;

        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() {
                continue;
            }
            if let Some(rest) = line.strip_prefix("# ") {
                if let Some(meta) = parse_meta_comment(rest) {
                    pending_meta = Some(meta);
                }
                continue;
            }
            if line.starts_with('#') {
                continue;
            }
            if let Ok(bridge) = line.parse::<BridgeLine>() {
                if !usable_for_tor(&bridge) {
                    pending_meta = None;
                    continue;
                }
                let meta = pending_meta.take().unwrap_or_default();
                let entry = Entry {
                    bridge,
                    last_ok: meta.last_ok,
                    last_attempt: meta.last_attempt,
                    last_latency: meta.last_latency,
                    fails: meta.fails,
                    ok_count: meta.ok_count,
                    channel_ok_count: meta.channel_ok_count,
                    last_channel_ok: meta.last_channel_ok,
                    verified_count: meta.verified_count,
                    last_verified: meta.last_verified,
                    last_verification_attempt: meta.last_verification_attempt,
                    circuit_fails: meta.circuit_fails,
                    last_circuit_observation: meta.last_circuit_observation,
                    sources: meta.sources,
                };
                entries.insert(entry.key(), entry);
            } else {
                pending_meta = None;
            }
        }

        Ok(Self { path, entries })
    }

    /// Record a successful probe: reset the failure counter and stamp the
    /// success time + latency. (Test helper; production goes through
    /// [`Self::note_probe_round`].)
    #[cfg(test)]
    fn record(&mut self, bridge: BridgeLine, latency: Duration) {
        self.record_at(bridge, latency, OffsetDateTime::now_utc());
    }

    fn record_at(&mut self, bridge: BridgeLine, latency: Duration, now: OffsetDateTime) {
        let key = key_of(&bridge);
        let e = self.entries.entry(key).or_insert_with(|| Entry {
            bridge: bridge.clone(),
            last_ok: None,
            last_attempt: now,
            last_latency: latency,
            fails: 0,
            ok_count: 0,
            channel_ok_count: 0,
            last_channel_ok: None,
            verified_count: 0,
            last_verified: None,
            last_verification_attempt: None,
            circuit_fails: 0,
            last_circuit_observation: now,
            sources: Default::default(),
        });
        e.bridge = bridge;
        e.last_ok = Some(now);
        e.last_attempt = now;
        e.last_latency = latency;
        e.fails = 0;
        e.ok_count = e.ok_count.saturating_add(1);
    }

    /// Apply the outcome of a probe round and prune dead bridges.
    ///
    /// `probed` is every bridge that was attempted; `alive` is the subset
    /// that responded (with latency). A reachable bridge resets to
    /// healthy; an unreachable one bumps its `fails` counter at most once
    /// per `fail_window`. Any bridge whose `fails` reaches `max_fails`
    /// **or** whose `circuit_fails` reaches `max_circuit_fails` is removed
    /// from the store and returned, so the caller can also drop it from
    /// the config.
    ///
    /// Pure w.r.t. `now` so it is unit-testable.
    pub fn note_probe_round(
        &mut self,
        probed: &[BridgeLine],
        alive: &[(BridgeLine, Duration)],
        now: OffsetDateTime,
        fail_window: Duration,
        max_fails: u32,
        max_circuit_fails: u32,
    ) -> Vec<BridgeLine> {
        use std::collections::HashSet;
        let alive_keys: HashSet<Key> = alive.iter().map(|(b, _)| key_of(b)).collect();

        for (bridge, latency) in alive {
            self.record_at(bridge.clone(), *latency, now);
        }
        for bridge in probed {
            if alive_keys.contains(&key_of(bridge)) {
                continue;
            }
            self.note_failure_at(bridge, now, fail_window);
        }

        self.prune(max_fails, max_circuit_fails)
    }

    /// Record a circuit-layer failure observed from arti's tracing events.
    /// Rate-limited: at most one bump per `window`. Returns true if the
    /// counter was incremented this call. If the bridge is unknown to the
    /// store, it is inserted with `circuit_fails = 1`.
    ///
    /// Pure w.r.t. `now` for unit testing.
    pub fn note_circuit_failure_at(
        &mut self,
        bridge: &BridgeLine,
        now: OffsetDateTime,
        window: Duration,
    ) -> bool {
        let key = key_of(bridge);
        match self.entries.get_mut(&key) {
            Some(e) => {
                if now - e.last_circuit_observation >= window {
                    e.circuit_fails = e.circuit_fails.saturating_add(1);
                    e.last_circuit_observation = now;
                    true
                } else {
                    false
                }
            }
            None => {
                self.entries.insert(
                    key,
                    Entry {
                        bridge: bridge.clone(),
                        last_ok: None,
                        last_attempt: now,
                        last_latency: Duration::ZERO,
                        fails: 0,
                        ok_count: 0,
                        channel_ok_count: 0,
                        last_channel_ok: None,
                        verified_count: 0,
                        last_verified: None,
                        last_verification_attempt: None,
                        circuit_fails: 1,
                        last_circuit_observation: now,
                        sources: Default::default(),
                    },
                );
                true
            }
        }
    }

    /// Mark a bridge as permanently unusable, regardless of the caller's
    /// failure window or threshold.
    ///
    /// Most channel failures are transient and deserve the rate-limited
    /// counting `note_circuit_failure_at` does. Some are verdicts: a relay whose
    /// identity does not match the fingerprint in the bridge line will never
    /// match it, because the line is stale rather than the relay unreachable.
    /// Counting those slowly means re-selecting a known-dead bridge for hours,
    /// and they are especially costly for webtunnel, where the endpoint stays
    /// perfectly reachable and so keeps ranking well.
    pub fn note_permanent_failure_at(&mut self, bridge: &BridgeLine, now: OffsetDateTime) {
        let key = key_of(bridge);
        let entry = self.entries.entry(key).or_insert_with(|| Entry {
            bridge: bridge.clone(),
            last_ok: None,
            last_attempt: now,
            last_latency: Duration::ZERO,
            fails: 0,
            ok_count: 0,
            channel_ok_count: 0,
            last_channel_ok: None,
            verified_count: 0,
            last_verified: None,
            last_verification_attempt: None,
            circuit_fails: 0,
            last_circuit_observation: now,
            sources: Default::default(),
        });
        entry.circuit_fails = RETIRED_CIRCUIT_FAILS;
        entry.last_circuit_observation = now;
    }

    /// Credit `source` with having offered `bridge`.
    ///
    /// Additive rather than overwriting: the same line is routinely published
    /// by several collectors, and crediting only the first would make every
    /// other one look barren for bridges it genuinely supplies. Creates a
    /// bare entry if the bridge has not been probed yet, so a source can be
    /// judged even before its bridges have been tried.
    pub fn note_source_at(&mut self, bridge: &BridgeLine, source: &str, now: OffsetDateTime) {
        let entry = self.entries.entry(key_of(bridge)).or_insert_with(|| Entry {
            bridge: bridge.clone(),
            last_ok: None,
            last_attempt: now,
            last_latency: Duration::ZERO,
            fails: 0,
            ok_count: 0,
            channel_ok_count: 0,
            last_channel_ok: None,
            verified_count: 0,
            last_verified: None,
            last_verification_attempt: None,
            circuit_fails: 0,
            last_circuit_observation: now,
            sources: Default::default(),
        });
        entry.sources.insert(source.to_owned());
    }

    /// Bridges that have actually carried a Tor channel, most recently first.
    ///
    /// Stricter than [`healthiest_bridges`](Self::healthiest_bridges), which
    /// also admits bridges that merely answered a reachability probe. For
    /// handing bridges to someone else that difference is the whole point: the
    /// recipient is typically offline at import and cannot check anything, so
    /// whatever is passed on has to be already known good rather than merely
    /// plausible. A webtunnel bridge in particular can answer probes forever
    /// while the relay behind its website is long gone.
    pub fn channel_proven_bridges(&self, limit: usize) -> Vec<BridgeLine> {
        let mut proven: Vec<&Entry> = self
            .entries
            .values()
            .filter(|e| e.channel_ok_count > 0 && !e.is_retired())
            .collect();
        proven.sort_by(|a, b| {
            b.last_channel_ok
                .cmp(&a.last_channel_ok)
                .then_with(|| b.channel_ok_count.cmp(&a.channel_ok_count))
        });
        proven
            .into_iter()
            .take(limit)
            .map(|e| e.bridge.clone())
            .collect()
    }

    /// What each source has actually yielded, keyed by its label.
    ///
    /// A source is judged by the bridges it supplied, not by whether its fetch
    /// succeeded — those answer different questions, and only the first one
    /// matters. A collector that has stopped regenerating keeps returning HTTP
    /// 200 with hundreds of lines indefinitely.
    pub fn source_summary(&self) -> Vec<SourceStats> {
        let mut by_source: BTreeMap<String, SourceStats> = BTreeMap::new();
        for entry in self.entries.values() {
            for label in &entry.sources {
                let stats = by_source
                    .entry(label.clone())
                    .or_insert_with(|| SourceStats {
                        label: label.clone(),
                        ..SourceStats::default()
                    });
                stats.offered += 1;
                if entry.is_retired() {
                    stats.retired += 1;
                    continue;
                }
                if entry.fails == 0 && entry.ok_count > 0 {
                    stats.alive += 1;
                }
                if entry.channel_ok_count > 0 {
                    stats.channel_proven += 1;
                }
            }
        }
        by_source.into_values().collect()
    }

    /// Sources credited with a bridge, empty when it predates attribution.
    pub fn sources_of(&self, bridge: &BridgeLine) -> Vec<String> {
        self.entries
            .get(&key_of(bridge))
            .map(|e| e.sources.iter().cloned().collect())
            .unwrap_or_default()
    }

    /// Per-transport counts and freshest timestamps, for a status display.
    ///
    /// Only covers bridges the store has seen. The configured total is not
    /// knowable here — that lives in the caller's own bridge list — and the
    /// difference between the two is itself informative: a large configured
    /// pool with few known entries means most of it has never been probed.
    pub fn transport_summary(&self) -> Vec<TransportStats> {
        let mut by_transport: BTreeMap<String, TransportStats> = BTreeMap::new();
        for entry in self.entries.values() {
            let name = entry
                .bridge
                .transport
                .clone()
                .unwrap_or_else(|| "plain".to_owned());
            let stats = by_transport
                .entry(name.clone())
                .or_insert_with(|| TransportStats {
                    transport: name,
                    ..TransportStats::default()
                });
            stats.known += 1;
            if entry.is_retired() {
                stats.retired += 1;
                // A retired bridge is excluded from the usable counts even
                // though its probe record looks perfect — that record is
                // exactly what makes it misleading.
                continue;
            }
            if entry.fails == 0 && entry.ok_count > 0 {
                stats.alive += 1;
            }
            if entry.channel_ok_count > 0 {
                stats.channel_proven += 1;
            }
            if let Some(ok) = entry.last_ok {
                stats.last_probe_ok = stats.last_probe_ok.max(Some(ok));
            }
            stats.last_channel_ok = stats.last_channel_ok.max(entry.last_channel_ok);
        }
        by_transport.into_values().collect()
    }

    /// Whether this bridge has been retired, i.e. proven unusable as configured
    /// rather than just unreliable. Callers selecting candidates should skip
    /// these: they stay reachable, so reachability-based checks keep voting for
    /// them.
    pub fn is_retired(&self, bridge: &BridgeLine) -> bool {
        self.entries
            .get(&key_of(bridge))
            .is_some_and(Entry::is_retired)
    }

    /// Whether `bridge`'s most recent probe attempt was today (UTC, by `today`'s date) and it
    /// failed (`fails > 0` -- a success would have reset it to zero). Lets a caller skip
    /// re-checking a bridge already known dead as of earlier today without waiting through its
    /// live timeout again; unknown to the store at all reads as "not known dead", not "dead".
    pub fn failed_today(&self, bridge: &BridgeLine, today: OffsetDateTime) -> bool {
        self.entries
            .get(&key_of(bridge))
            .is_some_and(|e| e.fails > 0 && e.last_attempt.date() == today.date())
    }

    /// Record a circuit-layer success observed from arti's tracing events:
    /// resets `circuit_fails` to 0 and stamps `last_circuit_observation`.
    /// No-op for an unknown bridge — circuit successes only matter for
    /// bridges we are tracking via TCP probes too.
    pub fn note_circuit_success_at(&mut self, bridge: &BridgeLine, now: OffsetDateTime) {
        if let Some(e) = self.entries.get_mut(&key_of(bridge)) {
            e.circuit_fails = 0;
            e.last_circuit_observation = now;
        }
    }

    /// Record a successful pluggable-transport channel warm-up. This is
    /// deliberately separate from TCP probe and end-to-end circuit counters:
    /// a warm channel is a strong rotation signal, but it is not proof that a
    /// multi-hop circuit can carry arbitrary traffic.
    pub fn note_channel_success_at(&mut self, bridge: &BridgeLine, now: OffsetDateTime) {
        if let Some(e) = self.entries.get_mut(&key_of(bridge)) {
            e.channel_ok_count = e.channel_ok_count.saturating_add(1);
            e.last_channel_ok = Some(now);
        }
    }

    /// Record that a full circuit through this bridge actually reached the
    /// open internet (`verify_bridge_reachable`, not merely a channel open).
    /// No-op if the bridge is not already tracked -- verification only ever
    /// runs against bridges the store already knows about (channel-proven
    /// candidates), never as a way to introduce a new entry.
    pub fn note_circuit_verified_at(&mut self, bridge: &BridgeLine, now: OffsetDateTime) {
        if let Some(e) = self.entries.get_mut(&key_of(bridge)) {
            e.verified_count = e.verified_count.saturating_add(1);
            e.last_verified = Some(now);
            e.last_verification_attempt = Some(now);
        }
    }

    /// Advance verification scheduling even when the check failed.
    pub fn note_verification_attempt_at(&mut self, bridge: &BridgeLine, now: OffsetDateTime) {
        if let Some(entry) = self.entries.get_mut(&key_of(bridge)) {
            entry.last_verification_attempt = Some(now);
        }
    }

    /// Bump the failure counter for one bridge, respecting the rate limit.
    /// Returns true if the counter was incremented this call.
    fn note_failure_at(
        &mut self,
        bridge: &BridgeLine,
        now: OffsetDateTime,
        window: Duration,
    ) -> bool {
        let key = key_of(bridge);
        match self.entries.get_mut(&key) {
            Some(e) => {
                // Rate-limit: only one increment per `window`.
                if now - e.last_attempt >= window {
                    e.fails = e.fails.saturating_add(1);
                    e.last_attempt = now;
                    true
                } else {
                    false
                }
            }
            None => {
                // First time we see this bridge and it already failed.
                self.entries.insert(
                    key,
                    Entry {
                        bridge: bridge.clone(),
                        last_ok: None,
                        last_attempt: now,
                        last_latency: Duration::ZERO,
                        fails: 1,
                        ok_count: 0,
                        channel_ok_count: 0,
                        last_channel_ok: None,
                        verified_count: 0,
                        last_verified: None,
                        last_verification_attempt: None,
                        circuit_fails: 0,
                        last_circuit_observation: now,
                        sources: Default::default(),
                    },
                );
                true
            }
        }
    }

    /// Remove and return every bridge whose `fails` reached `max_fails`
    /// or whose `circuit_fails` reached `max_circuit_fails`.
    fn prune(&mut self, max_fails: u32, max_circuit_fails: u32) -> Vec<BridgeLine> {
        let dead: Vec<Key> = self
            .entries
            .iter()
            .filter(|(_, e)| e.fails >= max_fails || e.circuit_fails >= max_circuit_fails)
            .map(|(k, _)| k.clone())
            .collect();
        dead.into_iter()
            .filter_map(|k| self.entries.remove(&k).map(|e| e.bridge))
            .collect()
    }

    /// Serialise the store back to disk via a sibling temp file + rename.
    pub fn save(&self) -> Result<()> {
        let now = OffsetDateTime::now_utc();
        let dir = self.path.parent().unwrap_or_else(|| Path::new("."));
        let file_name = self
            .path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "tor-socks5.alive-bridges.log".to_string());
        let tmp = dir.join(format!(".{file_name}.{}.tmp", std::process::id()));

        let mut out = String::new();
        out.push_str(HEADER_LINE1);
        out.push('\n');
        out.push_str(HEADER_LINE2_PREFIX);
        out.push_str(&format_iso(now));
        out.push('.');
        out.push('\n');
        out.push('\n');

        // Healthy + most-recently-ok first.
        let mut sorted: Vec<&Entry> = self.entries.values().collect();
        sorted.sort_by(|a, b| a.fails.cmp(&b.fails).then(b.last_ok.cmp(&a.last_ok)));

        for e in sorted {
            out.push_str("# fails=");
            out.push_str(&e.fails.to_string());
            out.push_str(" seen=");
            out.push_str(&e.ok_count.to_string());
            out.push_str(" attempt=");
            out.push_str(&format_iso(e.last_attempt));
            out.push_str(" ok=");
            out.push_str(&e.last_ok.map(format_iso).unwrap_or_else(|| "-".to_string()));
            out.push_str(" latency=");
            out.push_str(&e.last_latency.as_millis().to_string());
            out.push_str("ms chseen=");
            out.push_str(&e.channel_ok_count.to_string());
            out.push_str(" chok=");
            out.push_str(
                &e.last_channel_ok
                    .map(format_iso)
                    .unwrap_or_else(|| "-".to_string()),
            );
            out.push_str(" evseen=");
            out.push_str(&e.verified_count.to_string());
            out.push_str(" evok=");
            out.push_str(
                &e.last_verified
                    .map(format_iso)
                    .unwrap_or_else(|| "-".to_string()),
            );
            if let Some(attempt) = e.last_verification_attempt {
                // Optional metadata remains readable by earlier versions.
                out.push_str(" evtry=");
                out.push_str(&format_iso(attempt));
            }
            out.push_str(" cfails=");
            out.push_str(&e.circuit_fails.to_string());
            out.push_str(" cobs=");
            out.push_str(&format_iso(e.last_circuit_observation));
            // Omitted when unknown, so entries written before attribution
            // existed round-trip unchanged.
            if !e.sources.is_empty() {
                out.push_str(" src=");
                out.push_str(&e.sources.iter().cloned().collect::<Vec<_>>().join(","));
            }
            out.push('\n');
            out.push_str(&e.bridge.to_string());
            out.push('\n');
            out.push('\n');
        }

        if let Some(parent) = self.path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent).ok();
            }
        }
        {
            let mut f =
                fs::File::create(&tmp).with_context(|| format!("create {}", tmp.display()))?;
            f.write_all(out.as_bytes())
                .with_context(|| format!("write {}", tmp.display()))?;
            f.sync_all()
                .with_context(|| format!("fsync {}", tmp.display()))?;
        }
        fs::rename(&tmp, &self.path)
            .with_context(|| format!("rename {} → {}", tmp.display(), self.path.display()))?;
        Ok(())
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Number of bridges currently in a healthy TCP state (`fails == 0`)
    /// per the last probe round. Surfaced for the stale-channel watchdog,
    /// which must distinguish "all circuits fail but bridges are
    /// reachable" (stale channels → rebuild the client) from "bridges are
    /// genuinely unreachable" (the bridge maintenance loop's own job).
    #[must_use]
    pub fn alive_count(&self) -> usize {
        self.entries.values().filter(|e| e.fails == 0).count()
    }

    /// Cumulative successful-probe count for a bridge (0 if unknown). This
    /// is the persistent stability signal used to order bridges for arti:
    /// a higher count means the bridge has proven reachable more often.
    #[must_use]
    pub fn ok_count(&self, bridge: &BridgeLine) -> u32 {
        self.entries.get(&key_of(bridge)).map_or(0, |e| e.ok_count)
    }

    /// Circuit-layer consecutive failure count for a bridge (0 if unknown).
    /// Surfaced by arti's tracing events; used to prune bridges that pass
    /// TCP probes but can't carry multi-hop traffic. Also used by the
    /// bridge-warmer (`bridge_warmer.rs`) to rank candidates for channel
    /// warming — a bridge accumulating circuit failures is deprioritized
    /// even if its TCP probes still succeed.
    #[must_use]
    pub fn circuit_fails(&self, bridge: &BridgeLine) -> u32 {
        self.entries
            .get(&key_of(bridge))
            .map_or(0, |e| e.circuit_fails)
    }

    /// When the circuit-failure counter for a bridge was last touched (bumped
    /// or reset), if the bridge is known to the store. `None` covers "not
    /// tracked here". Surfaced for the soft-failover watchdog
    /// (`apps/socks5-proxy/src/tor_watchdog.rs`), which must only signal guard
    /// failures on evidence produced by the *current* process run — a
    /// `circuit_fails` count inherited from a previous run's store file
    /// (possibly days old, per docs/plans/2026-08-28-stability-plan.md §1b)
    /// must not arm a guard-failure signal seconds after boot. Note: entries
    /// parsed from legacy store lines without a `cobs=` field carry the Unix
    /// epoch here, which naturally compares as stale.
    #[must_use]
    pub fn last_circuit_observation(&self, bridge: &BridgeLine) -> Option<OffsetDateTime> {
        self.entries
            .get(&key_of(bridge))
            .map(|e| e.last_circuit_observation)
    }

    /// Number of successful PT/channel warm-ups for a bridge.
    #[must_use]
    pub fn channel_ok_count(&self, bridge: &BridgeLine) -> u32 {
        self.entries
            .get(&key_of(bridge))
            .map_or(0, |e| e.channel_ok_count)
    }

    /// Number of times a full circuit through this bridge was proven to
    /// reach the open internet. `0` covers both "never checked" and "the
    /// bridge is not even tracked".
    #[must_use]
    pub fn verified_count(&self, bridge: &BridgeLine) -> u32 {
        self.entries
            .get(&key_of(bridge))
            .map_or(0, |e| e.verified_count)
    }

    /// When a full circuit through this bridge last reached the open
    /// internet, if ever.
    #[must_use]
    pub fn last_verified(&self, bridge: &BridgeLine) -> Option<OffsetDateTime> {
        self.entries
            .get(&key_of(bridge))
            .and_then(|e| e.last_verified)
    }

    /// Channel-proven bridges (see [`Self::channel_proven_bridges`]) that either have never
    /// passed a full end-to-end circuit verification, or whose last one is older than
    /// `max_age` -- the candidate pool for the background watchdog's slow circuit-verify tick.
    /// Ranked oldest-verified (or never-verified) first, so the tick always makes progress
    /// through the whole channel-proven pool rather than repeatedly re-checking the same few
    /// bridges. Retired bridges are excluded.
    #[must_use]
    pub fn needing_circuit_verification(
        &self,
        now: OffsetDateTime,
        max_age: Duration,
        limit: usize,
    ) -> Vec<BridgeLine> {
        let mut due: Vec<&Entry> = self
            .entries
            .values()
            .filter(|e| e.channel_ok_count > 0 && !e.is_retired())
            .filter(|e| match e.last_verified {
                None => true,
                Some(t) => now - t >= max_age,
            })
            .collect();
        due.sort_by_key(|e| e.last_verification_attempt.or(e.last_verified));
        due.into_iter()
            .take(limit)
            .map(|e| e.bridge.clone())
            .collect()
    }

    /// Consecutive TCP-probe failure count for a bridge (0 if unknown, which
    /// also covers "never probed"). `0` means the last probe round saw this
    /// bridge as reachable — the same condition [`Self::alive_count`] counts
    /// bridges by. Used by the bridge-warmer to exclude TCP-unreachable
    /// bridges from the warming pool.
    #[must_use]
    pub fn tcp_fails(&self, bridge: &BridgeLine) -> u32 {
        self.entries.get(&key_of(bridge)).map_or(0, |e| e.fails)
    }

    /// Failure count for a bridge (0 if unknown). Test/diagnostic helper.
    #[cfg(test)]
    fn fails_of(&self, bridge: &BridgeLine) -> u32 {
        self.entries.get(&key_of(bridge)).map_or(0, |e| e.fails)
    }

    /// Bridges known reachable at the last probe round (`fails == 0`), ranked best-first by
    /// proven stability (`ok_count`, descending) then latency (ascending) -- the same ordering
    /// [`Self::note_probe_round`]'s caller applies to a freshly-probed round, read back from
    /// disk instead of requiring a new probe. A bridge with `ok_count == 0` (never yet seen
    /// reachable, even if it hasn't failed either) is excluded: absence of failure is not
    /// evidence the bridge actually works.
    #[must_use]
    pub fn healthiest_bridges(&self, limit: usize) -> Vec<BridgeLine> {
        let healthy: Vec<&Entry> = self
            .entries
            .values()
            // Retired bridges must be excluded rather than merely ranked low. A
            // retirement means the bridge answers but can never serve as
            // configured -- a stale fingerprint -- so it keeps a clean probe
            // record and an excellent latency, and any ranking that considers
            // only reachability promotes it straight back into the active pool.
            .filter(|e| e.fails == 0 && e.ok_count > 0 && !e.is_retired())
            .collect();
        Self::rank_and_take(healthy, limit)
    }

    /// Like [`healthiest_bridges`](Self::healthiest_bridges), but ranks only entries whose
    /// bridge appears in `candidates`, rather than the whole store.
    ///
    /// Ranking globally and then intersecting with a candidate set -- the obvious way to combine
    /// "healthiest" with "restricted to this pool" -- silently starves a small pool: a store
    /// dominated by one transport's history fills the global top `limit` before a smaller
    /// transport's own candidates are even considered, so "the healthiest of these 441 webtunnel
    /// bridges" could come back as five, not because only five are healthy, but because the rest
    /// don't outrank several thousand healthy obfs4 entries globally. Measured on a phone: this
    /// was the actual reason a webtunnel-preferred pool kept landing on a handful of bridges
    /// through every fix to the probing and warming logic above it -- all of them fed candidates
    /// through this same global-then-intersect pattern. Filtering to `candidates` first means a
    /// small pool's own best members always survive to be ranked.
    #[must_use]
    pub fn healthiest_among(&self, candidates: &[BridgeLine], limit: usize) -> Vec<BridgeLine> {
        use std::collections::HashSet;
        let allowed: HashSet<Key> = candidates.iter().map(key_of).collect();
        let healthy: Vec<&Entry> = self
            .entries
            .values()
            .filter(|e| {
                e.fails == 0 && e.ok_count > 0 && !e.is_retired() && allowed.contains(&e.key())
            })
            .collect();
        Self::rank_and_take(healthy, limit)
    }

    fn rank_and_take(mut healthy: Vec<&Entry>, limit: usize) -> Vec<BridgeLine> {
        healthy.sort_by(|a, b| {
            // End-to-end verified (a real circuit reached the open internet) outranks
            // merely channel-proven, which outranks merely TCP-reachable -- the same three
            // tiers `docs/design/real-connectivity-bridge-verification.md` documents.
            b.verified_count
                .cmp(&a.verified_count)
                .then_with(|| b.last_verified.cmp(&a.last_verified))
                .then_with(|| b.channel_ok_count.cmp(&a.channel_ok_count))
                .then_with(|| b.last_channel_ok.cmp(&a.last_channel_ok))
                .then_with(|| b.ok_count.cmp(&a.ok_count))
                .then(a.last_latency.cmp(&b.last_latency))
        });
        healthy
            .into_iter()
            .take(limit)
            .map(|e| e.bridge.clone())
            .collect()
    }
}

mod persistence;

use persistence::{format_iso, parse_meta_comment, Meta};

#[cfg(test)]
mod tests;
