//! Line-based on-disk format for the bridge health store: metadata parsing
//! and the atomic temp-file + rename save/load paths.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;

use anyhow::{Context, Result};
use bridge_line::BridgeLine;
use bridge_probe::usable_for_tor;
use time::format_description::well_known::Iso8601;
use time::OffsetDateTime;

use super::{BridgeStore, Entry};

/// Monotonic counter giving every save() call a unique temp-file name, even
/// when saves run concurrently within one process.
static SAVE_SEQ: AtomicU64 = AtomicU64::new(0);

const HEADER_LINE1: &str = "# Auto-generated by tor-socks5. Bridge reachability health.";
const HEADER_LINE2_PREFIX: &str = "# Last updated at ";

/// Parsed metadata-comment fields.
#[derive(Debug)]
pub(super) struct Meta {
    pub(super) last_ok: Option<OffsetDateTime>,
    pub(super) last_attempt: OffsetDateTime,
    pub(super) last_latency: Duration,
    pub(super) fails: u32,
    pub(super) ok_count: u32,
    pub(super) channel_ok_count: u32,
    pub(super) last_channel_ok: Option<OffsetDateTime>,
    pub(super) verified_count: u32,
    pub(super) last_verified: Option<OffsetDateTime>,
    pub(super) last_verification_attempt: Option<OffsetDateTime>,
    pub(super) circuit_fails: u32,
    pub(super) last_circuit_observation: OffsetDateTime,
    pub(super) sources: std::collections::BTreeSet<String>,
}

impl Default for Meta {
    fn default() -> Self {
        let epoch = OffsetDateTime::from_unix_timestamp(0).expect("epoch is valid");
        Self {
            last_ok: None,
            last_attempt: epoch,
            last_latency: Duration::ZERO,
            fails: 0,
            ok_count: 0,
            channel_ok_count: 0,
            last_channel_ok: None,
            verified_count: 0,
            last_verified: None,
            last_verification_attempt: None,
            circuit_fails: 0,
            sources: Default::default(),
            last_circuit_observation: epoch,
        }
    }
}

pub(super) fn parse_meta_comment(s: &str) -> Option<Meta> {
    // New format: `fails=N seen=M attempt=<iso> ok=<iso|-> latency=NNms`
    // plus optional `cfails=N cobs=<iso>` (active health observation).
    // Unknown tokens are ignored — forward-compatible.
    if s.starts_with("fails=") {
        let mut meta = Meta::default();
        for tok in s.split_whitespace() {
            if let Some(v) = tok.strip_prefix("fails=") {
                meta.fails = v.parse().ok()?;
            } else if let Some(v) = tok.strip_prefix("seen=") {
                meta.ok_count = v.parse().ok()?;
            } else if let Some(v) = tok.strip_prefix("attempt=") {
                meta.last_attempt = OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?;
            } else if let Some(v) = tok.strip_prefix("ok=") {
                meta.last_ok = if v == "-" {
                    None
                } else {
                    Some(OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?)
                };
            } else if let Some(v) = tok.strip_prefix("latency=") {
                let ms = v.strip_suffix("ms")?.parse::<u64>().ok()?;
                meta.last_latency = Duration::from_millis(ms);
            } else if let Some(v) = tok.strip_prefix("chseen=") {
                meta.channel_ok_count = v.parse().ok()?;
            } else if let Some(v) = tok.strip_prefix("chok=") {
                meta.last_channel_ok = if v == "-" {
                    None
                } else {
                    Some(OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?)
                };
            } else if let Some(v) = tok.strip_prefix("evseen=") {
                meta.verified_count = v.parse().ok()?;
            } else if let Some(v) = tok.strip_prefix("evok=") {
                meta.last_verified = if v == "-" {
                    None
                } else {
                    Some(OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?)
                };
            } else if let Some(v) = tok.strip_prefix("evtry=") {
                meta.last_verification_attempt =
                    Some(OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?);
            } else if let Some(v) = tok.strip_prefix("cfails=") {
                meta.circuit_fails = v.parse().ok()?;
            } else if let Some(v) = tok.strip_prefix("cobs=") {
                meta.last_circuit_observation = OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?;
            } else if let Some(v) = tok.strip_prefix("src=") {
                meta.sources = v
                    .split(',')
                    .filter(|s| !s.is_empty())
                    .map(str::to_owned)
                    .collect();
            }
        }
        return Some(meta);
    }

    // Legacy format: `<iso> latency=NNms` → treat as healthy at that time.
    let (when_part, rest) = s.split_once(' ')?;
    let when = OffsetDateTime::parse(when_part, &Iso8601::DEFAULT).ok()?;
    let lat_ms = rest
        .trim()
        .strip_prefix("latency=")?
        .strip_suffix("ms")?
        .parse::<u64>()
        .ok()?;
    Some(Meta {
        last_ok: Some(when),
        last_attempt: when,
        last_latency: Duration::from_millis(lat_ms),
        fails: 0,
        ok_count: 1,
        channel_ok_count: 0,
        last_channel_ok: None,
        verified_count: 0,
        last_verified: None,
        last_verification_attempt: None,
        circuit_fails: 0,
        sources: Default::default(),
        last_circuit_observation: when,
    })
}

pub(super) fn format_iso(t: OffsetDateTime) -> String {
    t.format(&Iso8601::DEFAULT)
        .unwrap_or_else(|_| "0000-00-00T00:00:00Z".to_string())
}

impl BridgeStore {
    /// Resolve the on-disk path of the store given the config path. When
    /// the config came from defaults we fall back to
    /// `./tor-socks5.alive-bridges.log`.
    pub fn resolve_path(config_path: Option<&Path>) -> PathBuf {
        match config_path {
            Some(cfg) => {
                let dir = cfg.parent().unwrap_or_else(|| Path::new("."));
                let stem = cfg
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_else(|| "tor-socks5".to_string());
                dir.join(format!("{stem}.alive-bridges.log"))
            }
            None => PathBuf::from("tor-socks5.alive-bridges.log"),
        }
    }

    /// Read the store from disk, silently ignoring malformed entries.
    /// Missing file → empty store.
    pub fn load(path: PathBuf) -> Result<Self> {
        let text = match fs::read_to_string(&path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                return Ok(Self {
                    path,
                    entries: BTreeMap::new(),
                });
            }
            Err(e) => return Err(e).with_context(|| format!("read {}", path.display())),
        };

        let mut entries = BTreeMap::new();
        let mut pending_meta: Option<Meta> = None;

        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() {
                continue;
            }
            if let Some(rest) = line.strip_prefix("# ") {
                if let Some(meta) = parse_meta_comment(rest) {
                    pending_meta = Some(meta);
                }
                continue;
            }
            if line.starts_with('#') {
                continue;
            }
            if let Ok(bridge) = line.parse::<BridgeLine>() {
                if !usable_for_tor(&bridge) {
                    pending_meta = None;
                    continue;
                }
                let meta = pending_meta.take().unwrap_or_default();
                let entry = Entry {
                    bridge,
                    last_ok: meta.last_ok,
                    last_attempt: meta.last_attempt,
                    last_latency: meta.last_latency,
                    fails: meta.fails,
                    ok_count: meta.ok_count,
                    channel_ok_count: meta.channel_ok_count,
                    last_channel_ok: meta.last_channel_ok,
                    verified_count: meta.verified_count,
                    last_verified: meta.last_verified,
                    last_verification_attempt: meta.last_verification_attempt,
                    circuit_fails: meta.circuit_fails,
                    last_circuit_observation: meta.last_circuit_observation,
                    sources: meta.sources,
                };
                entries.insert(entry.key(), entry);
            } else {
                pending_meta = None;
            }
        }

        Ok(Self { path, entries })
    }

    /// Serialise the store back to disk via a sibling temp file + rename.
    ///
    /// Temp-file names are unique per call (pid + a monotonic counter), so
    /// concurrent saves -- within this process or from other processes (e.g.
    /// a CLI subcommand) -- never share a temp file, and the final rename is
    /// atomic: readers see either the old or the new full file, never a torn
    /// state. Whole-file rename means two concurrent writers resolve as
    /// last-writer-wins per whole snapshot; the daemon serialises its own
    /// writes through a single owner, which is a higher-level contract not
    /// enforced here.
    pub fn save(&self) -> Result<()> {
        let now = OffsetDateTime::now_utc();
        let seq = SAVE_SEQ.fetch_add(1, Ordering::Relaxed);
        let tmp = self.temp_path(seq);

        let mut out = String::new();
        out.push_str(HEADER_LINE1);
        out.push('\n');
        out.push_str(HEADER_LINE2_PREFIX);
        out.push_str(&format_iso(now));
        out.push('.');
        out.push('\n');
        out.push('\n');

        // Healthy + most-recently-ok first.
        let mut sorted: Vec<&Entry> = self.entries.values().collect();
        sorted.sort_by(|a, b| a.fails.cmp(&b.fails).then(b.last_ok.cmp(&a.last_ok)));

        for e in sorted {
            out.push_str("# fails=");
            out.push_str(&e.fails.to_string());
            out.push_str(" seen=");
            out.push_str(&e.ok_count.to_string());
            out.push_str(" attempt=");
            out.push_str(&format_iso(e.last_attempt));
            out.push_str(" ok=");
            out.push_str(&e.last_ok.map(format_iso).unwrap_or_else(|| "-".to_string()));
            out.push_str(" latency=");
            out.push_str(&e.last_latency.as_millis().to_string());
            out.push_str("ms chseen=");
            out.push_str(&e.channel_ok_count.to_string());
            out.push_str(" chok=");
            out.push_str(
                &e.last_channel_ok
                    .map(format_iso)
                    .unwrap_or_else(|| "-".to_string()),
            );
            out.push_str(" evseen=");
            out.push_str(&e.verified_count.to_string());
            out.push_str(" evok=");
            out.push_str(
                &e.last_verified
                    .map(format_iso)
                    .unwrap_or_else(|| "-".to_string()),
            );
            if let Some(attempt) = e.last_verification_attempt {
                // Optional metadata remains readable by earlier versions.
                out.push_str(" evtry=");
                out.push_str(&format_iso(attempt));
            }
            out.push_str(" cfails=");
            out.push_str(&e.circuit_fails.to_string());
            out.push_str(" cobs=");
            out.push_str(&format_iso(e.last_circuit_observation));
            // Omitted when unknown, so entries written before attribution
            // existed round-trip unchanged.
            if !e.sources.is_empty() {
                out.push_str(" src=");
                out.push_str(&e.sources.iter().cloned().collect::<Vec<_>>().join(","));
            }
            out.push('\n');
            out.push_str(&e.bridge.to_string());
            out.push('\n');
            out.push('\n');
        }

        if let Some(parent) = self.path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent).ok();
            }
        }
        let write_out = || -> Result<()> {
            {
                let mut f =
                    fs::File::create(&tmp).with_context(|| format!("create {}", tmp.display()))?;
                f.write_all(out.as_bytes())
                    .with_context(|| format!("write {}", tmp.display()))?;
                f.sync_all()
                    .with_context(|| format!("fsync {}", tmp.display()))?;
            }
            fs::rename(&tmp, &self.path)
                .with_context(|| format!("rename {} → {}", tmp.display(), self.path.display()))?;
            Ok(())
        };
        match write_out() {
            Ok(()) => Ok(()),
            Err(err) => {
                // Best-effort cleanup of the failed temp file; never masks
                // the original error.
                let _ = fs::remove_file(&tmp);
                Err(err)
            }
        }
    }

    /// Sibling temp-file path for a save, unique per call via `seq`.
    pub(super) fn temp_path(&self, seq: u64) -> PathBuf {
        let dir = self.path.parent().unwrap_or_else(|| Path::new("."));
        let file_name = self
            .path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "tor-socks5.alive-bridges.log".to_string());
        dir.join(format!(".{file_name}.{}.{seq}.tmp", std::process::id()))
    }
}
