//! Persistent health store for bridges, kept next to the active config.
//!
//! Tracks every bridge we have probed, with its reachability history:
//! last successful probe, last failure-counter bump, and a `fails`
//! counter. The store drives bridge lifecycle:
//!
//! * a successful probe resets `fails` to 0 and stamps `ok`;
//! * a failed probe bumps `fails` — but at most once per `fail_window`
//!   (so a burst of retries counts once), stamping `attempt`;
//! * once `fails` reaches `max_fails`, the bridge is pruned (returned to
//!   the caller so it can also be dropped from the config).
//!
//! Failures are observed at the **probe** layer (TCP / obfs4 / webtunnel
//! reachability), which is what this process controls directly — arti
//! owns the live bridge connections and does not surface per-bridge
//! runtime failures to us.
//!
//! File format (line-based, plain text), one metadata comment per bridge:
//!
//! ```text
//! # fails=0 attempt=2026-05-14T15:00:12Z ok=2026-05-14T15:00:12Z latency=234ms
//! obfs4 1.2.3.4:80 ABCDEF... cert=... iat-mode=0
//! ```
//!
//! Dedup key: `(transport, addr, fingerprint)`.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{Context, Result};
use bridge_line::BridgeLine;
use time::format_description::well_known::Iso8601;
use time::OffsetDateTime;

const HEADER_LINE1: &str = "# Auto-generated by tor-socks5. Bridge reachability health.";
const HEADER_LINE2_PREFIX: &str = "# Last updated at ";

type Key = (Option<String>, SocketAddr, Option<String>);

#[derive(Debug, Clone)]
struct Entry {
    bridge: BridgeLine,
    /// Last time a probe succeeded, if ever.
    last_ok: Option<OffsetDateTime>,
    /// Last time the failure counter was touched (bumped or reset). Used
    /// to rate-limit `fails` increments to once per `fail_window`.
    last_attempt: OffsetDateTime,
    /// Latency of the last successful probe.
    last_latency: Duration,
    /// Consecutive TCP-probe failure count (reset to 0 on any TCP success).
    fails: u32,
    /// Cumulative count of successful probes over the bridge's lifetime.
    /// Never reset — a long-lived, frequently-reachable bridge accrues a
    /// high count, so this is our persistent **stability** signal (used to
    /// order bridges for arti: more-proven first, then by latency).
    ok_count: u32,
    /// Consecutive **circuit-layer** failure count, observed from arti's
    /// own tracing events (per-guard usability reports). Distinct from
    /// `fails` (TCP-probe layer): a bridge whose TCP/TLS works but whose
    /// descriptor or fingerprint is stale answers reachability probes yet
    /// can't carry multi-hop circuits. Resets to 0 on a circuit success.
    circuit_fails: u32,
    /// Last time the circuit-failure counter was touched (bumped or reset).
    /// Used to rate-limit `circuit_fails` to once per
    /// `circuit_observation_window` (arti retries quickly; we mustn't
    /// count each retry as a fresh failure).
    last_circuit_observation: OffsetDateTime,
}

impl Entry {
    fn key(&self) -> Key {
        key_of(&self.bridge)
    }
}

fn key_of(b: &BridgeLine) -> Key {
    (b.transport.clone(), b.addr, b.fingerprint.clone())
}

#[derive(Debug)]
pub struct BridgeStore {
    path: PathBuf,
    entries: BTreeMap<Key, Entry>,
}

impl BridgeStore {
    /// Resolve the on-disk path of the store given the config path. When
    /// the config came from defaults we fall back to
    /// `./tor-socks5.alive-bridges.log`.
    pub fn resolve_path(config_path: Option<&Path>) -> PathBuf {
        match config_path {
            Some(cfg) => {
                let dir = cfg.parent().unwrap_or_else(|| Path::new("."));
                let stem = cfg
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_else(|| "tor-socks5".to_string());
                dir.join(format!("{stem}.alive-bridges.log"))
            }
            None => PathBuf::from("tor-socks5.alive-bridges.log"),
        }
    }

    /// Read the store from disk, silently ignoring malformed entries.
    /// Missing file → empty store.
    pub fn load(path: PathBuf) -> Result<Self> {
        let text = match fs::read_to_string(&path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                return Ok(Self {
                    path,
                    entries: BTreeMap::new(),
                });
            }
            Err(e) => return Err(e).with_context(|| format!("read {}", path.display())),
        };

        let mut entries = BTreeMap::new();
        let mut pending_meta: Option<Meta> = None;

        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() {
                continue;
            }
            if let Some(rest) = line.strip_prefix("# ") {
                if let Some(meta) = parse_meta_comment(rest) {
                    pending_meta = Some(meta);
                }
                continue;
            }
            if line.starts_with('#') {
                continue;
            }
            if let Ok(bridge) = line.parse::<BridgeLine>() {
                let meta = pending_meta.take().unwrap_or_default();
                let entry = Entry {
                    bridge,
                    last_ok: meta.last_ok,
                    last_attempt: meta.last_attempt,
                    last_latency: meta.last_latency,
                    fails: meta.fails,
                    ok_count: meta.ok_count,
                    circuit_fails: meta.circuit_fails,
                    last_circuit_observation: meta.last_circuit_observation,
                };
                entries.insert(entry.key(), entry);
            } else {
                pending_meta = None;
            }
        }

        Ok(Self { path, entries })
    }

    /// Record a successful probe: reset the failure counter and stamp the
    /// success time + latency. (Test helper; production goes through
    /// [`Self::note_probe_round`].)
    #[cfg(test)]
    fn record(&mut self, bridge: BridgeLine, latency: Duration) {
        self.record_at(bridge, latency, OffsetDateTime::now_utc());
    }

    fn record_at(&mut self, bridge: BridgeLine, latency: Duration, now: OffsetDateTime) {
        let key = key_of(&bridge);
        let e = self.entries.entry(key).or_insert_with(|| Entry {
            bridge: bridge.clone(),
            last_ok: None,
            last_attempt: now,
            last_latency: latency,
            fails: 0,
            ok_count: 0,
            circuit_fails: 0,
            last_circuit_observation: now,
        });
        e.bridge = bridge;
        e.last_ok = Some(now);
        e.last_attempt = now;
        e.last_latency = latency;
        e.fails = 0;
        e.ok_count = e.ok_count.saturating_add(1);
    }

    /// Apply the outcome of a probe round and prune dead bridges.
    ///
    /// `probed` is every bridge that was attempted; `alive` is the subset
    /// that responded (with latency). A reachable bridge resets to
    /// healthy; an unreachable one bumps its `fails` counter at most once
    /// per `fail_window`. Any bridge whose `fails` reaches `max_fails`
    /// **or** whose `circuit_fails` reaches `max_circuit_fails` is removed
    /// from the store and returned, so the caller can also drop it from
    /// the config.
    ///
    /// Pure w.r.t. `now` so it is unit-testable.
    pub fn note_probe_round(
        &mut self,
        probed: &[BridgeLine],
        alive: &[(BridgeLine, Duration)],
        now: OffsetDateTime,
        fail_window: Duration,
        max_fails: u32,
        max_circuit_fails: u32,
    ) -> Vec<BridgeLine> {
        use std::collections::HashSet;
        let alive_keys: HashSet<Key> = alive.iter().map(|(b, _)| key_of(b)).collect();

        for (bridge, latency) in alive {
            self.record_at(bridge.clone(), *latency, now);
        }
        for bridge in probed {
            if alive_keys.contains(&key_of(bridge)) {
                continue;
            }
            self.note_failure_at(bridge, now, fail_window);
        }

        self.prune(max_fails, max_circuit_fails)
    }

    /// Record a circuit-layer failure observed from arti's tracing events.
    /// Rate-limited: at most one bump per `window`. Returns true if the
    /// counter was incremented this call. If the bridge is unknown to the
    /// store, it is inserted with `circuit_fails = 1`.
    ///
    /// Pure w.r.t. `now` for unit testing.
    pub fn note_circuit_failure_at(
        &mut self,
        bridge: &BridgeLine,
        now: OffsetDateTime,
        window: Duration,
    ) -> bool {
        let key = key_of(bridge);
        match self.entries.get_mut(&key) {
            Some(e) => {
                if now - e.last_circuit_observation >= window {
                    e.circuit_fails = e.circuit_fails.saturating_add(1);
                    e.last_circuit_observation = now;
                    true
                } else {
                    false
                }
            }
            None => {
                self.entries.insert(
                    key,
                    Entry {
                        bridge: bridge.clone(),
                        last_ok: None,
                        last_attempt: now,
                        last_latency: Duration::ZERO,
                        fails: 0,
                        ok_count: 0,
                        circuit_fails: 1,
                        last_circuit_observation: now,
                    },
                );
                true
            }
        }
    }

    /// Record a circuit-layer success observed from arti's tracing events:
    /// resets `circuit_fails` to 0 and stamps `last_circuit_observation`.
    /// No-op for an unknown bridge — circuit successes only matter for
    /// bridges we are tracking via TCP probes too.
    pub fn note_circuit_success_at(&mut self, bridge: &BridgeLine, now: OffsetDateTime) {
        if let Some(e) = self.entries.get_mut(&key_of(bridge)) {
            e.circuit_fails = 0;
            e.last_circuit_observation = now;
        }
    }

    /// Bump the failure counter for one bridge, respecting the rate limit.
    /// Returns true if the counter was incremented this call.
    fn note_failure_at(
        &mut self,
        bridge: &BridgeLine,
        now: OffsetDateTime,
        window: Duration,
    ) -> bool {
        let key = key_of(bridge);
        match self.entries.get_mut(&key) {
            Some(e) => {
                // Rate-limit: only one increment per `window`.
                if now - e.last_attempt >= window {
                    e.fails = e.fails.saturating_add(1);
                    e.last_attempt = now;
                    true
                } else {
                    false
                }
            }
            None => {
                // First time we see this bridge and it already failed.
                self.entries.insert(
                    key,
                    Entry {
                        bridge: bridge.clone(),
                        last_ok: None,
                        last_attempt: now,
                        last_latency: Duration::ZERO,
                        fails: 1,
                        ok_count: 0,
                        circuit_fails: 0,
                        last_circuit_observation: now,
                    },
                );
                true
            }
        }
    }

    /// Remove and return every bridge whose `fails` reached `max_fails`
    /// or whose `circuit_fails` reached `max_circuit_fails`.
    fn prune(&mut self, max_fails: u32, max_circuit_fails: u32) -> Vec<BridgeLine> {
        let dead: Vec<Key> = self
            .entries
            .iter()
            .filter(|(_, e)| e.fails >= max_fails || e.circuit_fails >= max_circuit_fails)
            .map(|(k, _)| k.clone())
            .collect();
        dead.into_iter()
            .filter_map(|k| self.entries.remove(&k).map(|e| e.bridge))
            .collect()
    }

    /// Serialise the store back to disk via a sibling temp file + rename.
    pub fn save(&self) -> Result<()> {
        let now = OffsetDateTime::now_utc();
        let dir = self.path.parent().unwrap_or_else(|| Path::new("."));
        let file_name = self
            .path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "tor-socks5.alive-bridges.log".to_string());
        let tmp = dir.join(format!(".{file_name}.{}.tmp", std::process::id()));

        let mut out = String::new();
        out.push_str(HEADER_LINE1);
        out.push('\n');
        out.push_str(HEADER_LINE2_PREFIX);
        out.push_str(&format_iso(now));
        out.push('.');
        out.push('\n');
        out.push('\n');

        // Healthy + most-recently-ok first.
        let mut sorted: Vec<&Entry> = self.entries.values().collect();
        sorted.sort_by(|a, b| a.fails.cmp(&b.fails).then(b.last_ok.cmp(&a.last_ok)));

        for e in sorted {
            out.push_str("# fails=");
            out.push_str(&e.fails.to_string());
            out.push_str(" seen=");
            out.push_str(&e.ok_count.to_string());
            out.push_str(" attempt=");
            out.push_str(&format_iso(e.last_attempt));
            out.push_str(" ok=");
            out.push_str(&e.last_ok.map(format_iso).unwrap_or_else(|| "-".to_string()));
            out.push_str(" latency=");
            out.push_str(&e.last_latency.as_millis().to_string());
            out.push_str("ms cfails=");
            out.push_str(&e.circuit_fails.to_string());
            out.push_str(" cobs=");
            out.push_str(&format_iso(e.last_circuit_observation));
            out.push('\n');
            out.push_str(&e.bridge.to_string());
            out.push('\n');
            out.push('\n');
        }

        if let Some(parent) = self.path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent).ok();
            }
        }
        {
            let mut f =
                fs::File::create(&tmp).with_context(|| format!("create {}", tmp.display()))?;
            f.write_all(out.as_bytes())
                .with_context(|| format!("write {}", tmp.display()))?;
            f.sync_all()
                .with_context(|| format!("fsync {}", tmp.display()))?;
        }
        fs::rename(&tmp, &self.path)
            .with_context(|| format!("rename {} → {}", tmp.display(), self.path.display()))?;
        Ok(())
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Number of bridges currently in a healthy TCP state (`fails == 0`)
    /// per the last probe round. Surfaced for the stale-channel watchdog,
    /// which must distinguish "all circuits fail but bridges are
    /// reachable" (stale channels → rebuild the client) from "bridges are
    /// genuinely unreachable" (the bridge maintenance loop's own job).
    #[must_use]
    pub fn alive_count(&self) -> usize {
        self.entries.values().filter(|e| e.fails == 0).count()
    }

    /// Cumulative successful-probe count for a bridge (0 if unknown). This
    /// is the persistent stability signal used to order bridges for arti:
    /// a higher count means the bridge has proven reachable more often.
    #[must_use]
    pub fn ok_count(&self, bridge: &BridgeLine) -> u32 {
        self.entries.get(&key_of(bridge)).map_or(0, |e| e.ok_count)
    }

    /// Circuit-layer consecutive failure count for a bridge (0 if unknown).
    /// Surfaced by arti's tracing events; used to prune bridges that pass
    /// TCP probes but can't carry multi-hop traffic.
    ///
    /// Exposed for diagnostics and the upcoming circuit-aware pruning flow
    /// (config knob `max_circuit_fails`, see issue #115); allow(dead_code)
    /// keeps clippy quiet while only tests exercise it.
    #[must_use]
    #[allow(dead_code)]
    pub fn circuit_fails(&self, bridge: &BridgeLine) -> u32 {
        self.entries
            .get(&key_of(bridge))
            .map_or(0, |e| e.circuit_fails)
    }

    /// Failure count for a bridge (0 if unknown). Test/diagnostic helper.
    #[cfg(test)]
    fn fails_of(&self, bridge: &BridgeLine) -> u32 {
        self.entries.get(&key_of(bridge)).map_or(0, |e| e.fails)
    }
}

/// Parsed metadata-comment fields.
#[derive(Debug)]
struct Meta {
    last_ok: Option<OffsetDateTime>,
    last_attempt: OffsetDateTime,
    last_latency: Duration,
    fails: u32,
    ok_count: u32,
    circuit_fails: u32,
    last_circuit_observation: OffsetDateTime,
}

impl Default for Meta {
    fn default() -> Self {
        let epoch = OffsetDateTime::from_unix_timestamp(0).expect("epoch is valid");
        Self {
            last_ok: None,
            last_attempt: epoch,
            last_latency: Duration::ZERO,
            fails: 0,
            ok_count: 0,
            circuit_fails: 0,
            last_circuit_observation: epoch,
        }
    }
}

fn parse_meta_comment(s: &str) -> Option<Meta> {
    // New format: `fails=N seen=M attempt=<iso> ok=<iso|-> latency=NNms`
    // plus optional `cfails=N cobs=<iso>` (active health observation).
    // Unknown tokens are ignored — forward-compatible.
    if s.starts_with("fails=") {
        let mut meta = Meta::default();
        for tok in s.split_whitespace() {
            if let Some(v) = tok.strip_prefix("fails=") {
                meta.fails = v.parse().ok()?;
            } else if let Some(v) = tok.strip_prefix("seen=") {
                meta.ok_count = v.parse().ok()?;
            } else if let Some(v) = tok.strip_prefix("attempt=") {
                meta.last_attempt = OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?;
            } else if let Some(v) = tok.strip_prefix("ok=") {
                meta.last_ok = if v == "-" {
                    None
                } else {
                    Some(OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?)
                };
            } else if let Some(v) = tok.strip_prefix("latency=") {
                let ms = v.strip_suffix("ms")?.parse::<u64>().ok()?;
                meta.last_latency = Duration::from_millis(ms);
            } else if let Some(v) = tok.strip_prefix("cfails=") {
                meta.circuit_fails = v.parse().ok()?;
            } else if let Some(v) = tok.strip_prefix("cobs=") {
                meta.last_circuit_observation = OffsetDateTime::parse(v, &Iso8601::DEFAULT).ok()?;
            }
        }
        return Some(meta);
    }

    // Legacy format: `<iso> latency=NNms` → treat as healthy at that time.
    let (when_part, rest) = s.split_once(' ')?;
    let when = OffsetDateTime::parse(when_part, &Iso8601::DEFAULT).ok()?;
    let lat_ms = rest
        .trim()
        .strip_prefix("latency=")?
        .strip_suffix("ms")?
        .parse::<u64>()
        .ok()?;
    Some(Meta {
        last_ok: Some(when),
        last_attempt: when,
        last_latency: Duration::from_millis(lat_ms),
        fails: 0,
        ok_count: 1,
        circuit_fails: 0,
        last_circuit_observation: when,
    })
}

fn format_iso(t: OffsetDateTime) -> String {
    t.format(&Iso8601::DEFAULT)
        .unwrap_or_else(|_| "0000-00-00T00:00:00Z".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_dir() -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static SEQ: AtomicU64 = AtomicU64::new(0);
        let seq = SEQ.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!(
            "tor-socks5-bridge-store-test-{}-{}",
            std::process::id(),
            seq
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn bridge(line: &str) -> BridgeLine {
        line.parse().expect("test bridge line parses")
    }

    const OBFS4_A: &str =
        "obfs4 1.2.3.4:80 ABCDEF0123456789ABCDEF0123456789ABCDEF01 cert=ZZZ iat-mode=0";
    const OBFS4_A_NEW_PARAMS: &str =
        "obfs4 1.2.3.4:80 ABCDEF0123456789ABCDEF0123456789ABCDEF01 cert=YYY iat-mode=1";
    const OBFS4_B: &str =
        "obfs4 5.6.7.8:443 0123456789ABCDEF0123456789ABCDEF01234567 cert=WWW iat-mode=0";

    const HOUR: Duration = Duration::from_secs(3600);
    const MAX_FAILS: u32 = 24;

    fn empty() -> BridgeStore {
        BridgeStore {
            path: PathBuf::from("mem.log"),
            entries: BTreeMap::new(),
        }
    }

    #[test]
    fn resolve_path_uses_config_dir_and_stem() {
        let p = BridgeStore::resolve_path(Some(Path::new("/etc/tor-socks5.ktav")));
        assert_eq!(
            p.file_name().unwrap().to_string_lossy(),
            "tor-socks5.alive-bridges.log"
        );
    }

    #[test]
    fn load_missing_file_is_empty() {
        let dir = tmp_dir();
        let store = BridgeStore::load(dir.join("does-not-exist.log")).expect("load");
        assert_eq!(store.len(), 0);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn record_save_load_roundtrip_with_health() {
        let dir = tmp_dir();
        let path = dir.join("alive.log");
        let mut s = BridgeStore::load(path.clone()).unwrap();
        s.record(bridge(OBFS4_A), Duration::from_millis(42));
        s.record(bridge(OBFS4_B), Duration::from_millis(11));
        s.save().unwrap();

        let loaded = BridgeStore::load(path.clone()).unwrap();
        assert_eq!(loaded.len(), 2);
        assert_eq!(loaded.fails_of(&bridge(OBFS4_A)), 0);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn ok_count_accumulates_and_persists() {
        let dir = tmp_dir();
        let path = dir.join("ok.log");
        let mut s = BridgeStore::load(path.clone()).unwrap();
        let b = bridge(OBFS4_A);
        s.record(b.clone(), Duration::from_millis(10));
        s.record(b.clone(), Duration::from_millis(20));
        assert_eq!(s.ok_count(&b), 2, "two successes accumulate");
        s.save().unwrap();
        let loaded = BridgeStore::load(path).unwrap();
        assert_eq!(
            loaded.ok_count(&bridge(OBFS4_A)),
            2,
            "seen= count persisted across save/load"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn dedup_key_is_transport_addr_fingerprint() {
        let mut s = empty();
        s.record(bridge(OBFS4_A), Duration::from_millis(100));
        s.record(bridge(OBFS4_A_NEW_PARAMS), Duration::from_millis(50));
        assert_eq!(s.len(), 1, "same key upserts");
    }

    #[test]
    fn failure_increments_then_rate_limited_within_window() {
        let mut s = empty();
        let b = bridge(OBFS4_A);
        let t0 = OffsetDateTime::from_unix_timestamp(1_000_000).unwrap();

        // First failure → counts (new entry).
        assert!(s.note_failure_at(&b, t0, HOUR));
        assert_eq!(s.fails_of(&b), 1);
        // Another failure 10 min later → within window → no increment.
        assert!(!s.note_failure_at(&b, t0 + Duration::from_secs(600), HOUR));
        assert_eq!(s.fails_of(&b), 1);
        // A failure just past the window → increments.
        assert!(s.note_failure_at(&b, t0 + HOUR + Duration::from_secs(1), HOUR));
        assert_eq!(s.fails_of(&b), 2);
    }

    #[test]
    fn success_resets_failure_counter() {
        let mut s = empty();
        let b = bridge(OBFS4_A);
        let t0 = OffsetDateTime::from_unix_timestamp(1_000_000).unwrap();
        s.note_failure_at(&b, t0, HOUR);
        s.note_failure_at(&b, t0 + HOUR + Duration::from_secs(1), HOUR);
        assert_eq!(s.fails_of(&b), 2);
        s.record_at(b.clone(), Duration::from_millis(5), t0 + 3 * HOUR);
        assert_eq!(s.fails_of(&b), 0, "success clears fails");
    }

    #[test]
    fn note_probe_round_prunes_after_max_fails() {
        let mut s = empty();
        let b = bridge(OBFS4_A);
        let probed = vec![b.clone()];
        let alive: Vec<(BridgeLine, Duration)> = vec![]; // always dead
        let mut now = OffsetDateTime::from_unix_timestamp(2_000_000).unwrap();

        // 23 failed rounds, one per window+ → fails climbs to 23, no prune.
        for _ in 0..(MAX_FAILS - 1) {
            let pruned = s.note_probe_round(&probed, &alive, now, HOUR, MAX_FAILS, u32::MAX);
            assert!(pruned.is_empty());
            now += HOUR + Duration::from_secs(1);
        }
        assert_eq!(s.fails_of(&b), MAX_FAILS - 1);
        // The 24th failure → prune.
        let pruned = s.note_probe_round(&probed, &alive, now, HOUR, MAX_FAILS, u32::MAX);
        assert_eq!(pruned.len(), 1, "bridge removed at max_fails");
        assert_eq!(s.len(), 0);
    }

    #[test]
    fn note_probe_round_alive_resets_and_dead_bumps() {
        let mut s = empty();
        let a = bridge(OBFS4_A);
        let d = bridge(OBFS4_B);
        let now = OffsetDateTime::from_unix_timestamp(3_000_000).unwrap();
        let probed = vec![a.clone(), d.clone()];
        let alive = vec![(a.clone(), Duration::from_millis(50))];
        let pruned = s.note_probe_round(&probed, &alive, now, HOUR, MAX_FAILS, u32::MAX);
        assert!(pruned.is_empty());
        assert_eq!(s.fails_of(&a), 0, "alive stays healthy");
        assert_eq!(s.fails_of(&d), 1, "dead bumped");
    }

    #[test]
    fn legacy_format_loads_as_healthy() {
        let dir = tmp_dir();
        let path = dir.join("legacy.log");
        std::fs::write(
            &path,
            format!("# 2026-05-18T12:00:00Z latency=42ms\n{OBFS4_A}\n"),
        )
        .unwrap();
        let loaded = BridgeStore::load(path).unwrap();
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded.fails_of(&bridge(OBFS4_A)), 0);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn health_format_roundtrips() {
        let dir = tmp_dir();
        let path = dir.join("h.log");
        let mut s = BridgeStore::load(path.clone()).unwrap();
        let b = bridge(OBFS4_A);
        let t0 = OffsetDateTime::from_unix_timestamp(1_700_000_000).unwrap();
        s.note_failure_at(&b, t0, HOUR);
        s.note_failure_at(&b, t0 + HOUR + Duration::from_secs(1), HOUR);
        s.save().unwrap();
        let loaded = BridgeStore::load(path).unwrap();
        assert_eq!(loaded.fails_of(&b), 2, "fails persisted across save/load");
        let _ = std::fs::remove_dir_all(&dir);
    }

    // -- Circuit-layer observation tests -------------------------------------

    const HALF_HOUR: Duration = Duration::from_secs(30 * 60);
    const MAX_CIRCUIT_FAILS: u32 = 5;

    #[test]
    fn circuit_failure_bumps_outside_window_rate_limits_inside() {
        let mut s = empty();
        let b = bridge(OBFS4_A);
        let t0 = OffsetDateTime::from_unix_timestamp(2_500_000).unwrap();

        // First observation creates the entry with circuit_fails=1.
        assert!(s.note_circuit_failure_at(&b, t0, HALF_HOUR));
        assert_eq!(s.circuit_fails(&b), 1);
        // Within the rate-limit window — no increment.
        assert!(!s.note_circuit_failure_at(&b, t0 + Duration::from_secs(60), HALF_HOUR));
        assert_eq!(s.circuit_fails(&b), 1);
        // Past the window — increments.
        assert!(s.note_circuit_failure_at(&b, t0 + HALF_HOUR + Duration::from_secs(1), HALF_HOUR));
        assert_eq!(s.circuit_fails(&b), 2);
    }

    #[test]
    fn circuit_success_resets_circuit_fails() {
        let mut s = empty();
        let b = bridge(OBFS4_A);
        let t0 = OffsetDateTime::from_unix_timestamp(2_500_000).unwrap();
        s.note_circuit_failure_at(&b, t0, HALF_HOUR);
        s.note_circuit_failure_at(&b, t0 + HALF_HOUR + Duration::from_secs(1), HALF_HOUR);
        assert_eq!(s.circuit_fails(&b), 2);
        s.note_circuit_success_at(&b, t0 + 2 * HALF_HOUR);
        assert_eq!(s.circuit_fails(&b), 0, "success clears circuit_fails");
    }

    #[test]
    fn circuit_success_is_noop_for_unknown_bridge() {
        let mut s = empty();
        let b = bridge(OBFS4_A);
        let now = OffsetDateTime::from_unix_timestamp(2_500_000).unwrap();
        s.note_circuit_success_at(&b, now);
        assert_eq!(s.len(), 0, "no entry created from a success-only signal");
        assert_eq!(s.circuit_fails(&b), 0);
    }

    #[test]
    fn note_probe_round_prunes_after_max_circuit_fails() {
        let mut s = empty();
        let b = bridge(OBFS4_A);
        let probed = vec![b.clone()];
        // TCP probe says alive — so `fails` stays 0 throughout.
        let alive = vec![(b.clone(), Duration::from_millis(50))];
        let mut now = OffsetDateTime::from_unix_timestamp(2_600_000).unwrap();

        // Drive circuit_fails up to (MAX_CIRCUIT_FAILS - 1).
        for _ in 0..(MAX_CIRCUIT_FAILS - 1) {
            s.note_circuit_failure_at(&b, now, HALF_HOUR);
            now += HALF_HOUR + Duration::from_secs(1);
        }
        // probe round with full health on TCP side, but circuit_fails close
        // to the threshold — still no prune yet.
        let pruned = s.note_probe_round(&probed, &alive, now, HOUR, MAX_FAILS, MAX_CIRCUIT_FAILS);
        assert!(pruned.is_empty());
        // ...but wait — note_probe_round resets `fails` and records success
        // on TCP. It does NOT touch circuit_fails (TCP and circuit layers are
        // independent). So circuit_fails is still MAX-1 here.
        assert_eq!(s.circuit_fails(&b), MAX_CIRCUIT_FAILS - 1);

        // One more circuit failure → reaches MAX_CIRCUIT_FAILS.
        s.note_circuit_failure_at(&b, now + HALF_HOUR + Duration::from_secs(1), HALF_HOUR);
        assert_eq!(s.circuit_fails(&b), MAX_CIRCUIT_FAILS);
        // Next probe round prunes despite TCP-healthy state.
        let pruned = s.note_probe_round(
            &probed,
            &alive,
            now + 2 * HOUR,
            HOUR,
            MAX_FAILS,
            MAX_CIRCUIT_FAILS,
        );
        assert_eq!(pruned.len(), 1, "TCP-alive bridge pruned on circuit_fails");
        assert_eq!(s.len(), 0);
    }

    #[test]
    fn circuit_metadata_persists_across_save_load() {
        let dir = tmp_dir();
        let path = dir.join("c.log");
        let mut s = BridgeStore::load(path.clone()).unwrap();
        let b = bridge(OBFS4_A);
        let t0 = OffsetDateTime::from_unix_timestamp(1_700_000_000).unwrap();
        // Make a TCP-healthy entry first so the bridge survives without
        // also crossing `fails` thresholds. Use `record_at` (not `record`)
        // so the entry's `last_circuit_observation` is in the same time
        // frame as the failures below — otherwise the rate-limit window
        // (last_circuit_observation = now_utc()) eats every bump that
        // happens "in the past" relative to wall time.
        s.record_at(b.clone(), Duration::from_millis(10), t0);
        s.note_circuit_failure_at(&b, t0 + HALF_HOUR + Duration::from_secs(1), HALF_HOUR);
        s.note_circuit_failure_at(&b, t0 + 2 * HALF_HOUR + Duration::from_secs(2), HALF_HOUR);
        assert_eq!(s.circuit_fails(&b), 2);
        s.save().unwrap();

        let loaded = BridgeStore::load(path).unwrap();
        assert_eq!(
            loaded.circuit_fails(&b),
            2,
            "cfails= persisted across save/load"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
