//! Persistent pool of **unverified** bridge candidates.
//!
//! Fetching bridge lists (network → public collectors) is decoupled from
//! probing them (network → the bridges) and from using them (the working
//! config that arti bootstraps on):
//!
//! * a **refresh** fetches the source lists and merges the newcomers here,
//!   deduplicated and minus anything already in the working config;
//! * a **drain** walks this pool lazily (one bridge at a time), promotes
//!   the reachable ones into the working config, and removes every probed
//!   candidate from the pool (reachable → promoted, dead → discarded).
//!
//! Stored next to the active config as `<stem>.candidates.log`, a scratch
//! staging file (plain bridge lines, one per line):
//!
//! ```text
//! # Auto-generated by tor-socks5. Unverified bridge candidate pool.
//! obfs4 1.2.3.4:80 ABCDEF... cert=... iat-mode=0
//! webtunnel [2001:db8::1]:443 0123... url=https://example.com/x ver=0.0.3
//! ```
//!
//! Dedup key: `(transport, addr, fingerprint)` — same as everywhere else.

use std::collections::HashSet;
use std::fs;
use std::io::Write;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use bridge_line::BridgeLine;

const HEADER: &str = "# Auto-generated by tor-socks5. Unverified bridge candidate pool.";
const DEFAULT_FILE: &str = "tor-socks5.candidates.log";

/// Dedup key shared with the config / health store.
pub type Key = (Option<String>, SocketAddr, Option<String>);

pub fn key_of(b: &BridgeLine) -> Key {
    (b.transport.clone(), b.addr, b.fingerprint.clone())
}

#[derive(Debug)]
pub struct CandidatePool {
    path: PathBuf,
    /// Insertion-ordered candidates, deduplicated by [`key_of`].
    bridges: Vec<BridgeLine>,
    keys: HashSet<Key>,
}

impl CandidatePool {
    /// Resolve the pool path from the config path: same dir + stem, fixed
    /// `.candidates.log` suffix (mirrors the alive-bridges log). Falls back
    /// to `./tor-socks5.candidates.log` for built-in defaults.
    pub fn resolve_path(config_path: Option<&Path>) -> PathBuf {
        match config_path {
            Some(cfg) => {
                let dir = cfg.parent().unwrap_or_else(|| Path::new("."));
                let stem = cfg
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_else(|| "tor-socks5".to_string());
                dir.join(format!("{stem}.candidates.log"))
            }
            None => PathBuf::from(DEFAULT_FILE),
        }
    }

    /// Load the pool, ignoring malformed/duplicate lines. Missing file →
    /// empty pool.
    pub fn load(path: PathBuf) -> Result<Self> {
        let mut pool = Self {
            path,
            bridges: Vec::new(),
            keys: HashSet::new(),
        };
        let text = match fs::read_to_string(&pool.path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(pool),
            Err(e) => return Err(e).with_context(|| format!("read {}", pool.path.display())),
        };
        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Ok(bridge) = line.parse::<BridgeLine>() {
                pool.push_unique(bridge);
            }
        }
        Ok(pool)
    }

    fn push_unique(&mut self, bridge: BridgeLine) -> bool {
        let key = key_of(&bridge);
        if self.keys.insert(key) {
            self.bridges.push(bridge);
            true
        } else {
            false
        }
    }

    /// Merge fetched candidates, skipping any already present in the pool
    /// or whose key is in `exclude` (the working set). Returns how many
    /// were newly added.
    pub fn merge(
        &mut self,
        fetched: impl IntoIterator<Item = BridgeLine>,
        exclude: &HashSet<Key>,
    ) -> usize {
        let mut added = 0;
        for bridge in fetched {
            if exclude.contains(&key_of(&bridge)) {
                continue;
            }
            if self.push_unique(bridge) {
                added += 1;
            }
        }
        added
    }

    /// Remove and return up to `n` candidates from the front of the pool.
    pub fn take(&mut self, n: usize) -> Vec<BridgeLine> {
        let n = n.min(self.bridges.len());
        let taken: Vec<BridgeLine> = self.bridges.drain(..n).collect();
        for b in &taken {
            self.keys.remove(&key_of(b));
        }
        taken
    }

    /// Put bridges back at the front of the pool (e.g. a taken batch that
    /// was not probed this round), preserving dedup.
    pub fn return_front(&mut self, bridges: Vec<BridgeLine>) {
        let mut prefix = Vec::with_capacity(bridges.len());
        for b in bridges {
            if self.keys.insert(key_of(&b)) {
                prefix.push(b);
            }
        }
        prefix.append(&mut self.bridges);
        self.bridges = prefix;
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.bridges.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.bridges.is_empty()
    }

    /// Atomic write via sibling temp file + rename.
    pub fn save(&self) -> Result<()> {
        let dir = self.path.parent().unwrap_or_else(|| Path::new("."));
        let file_name = self
            .path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| DEFAULT_FILE.to_string());
        let tmp = dir.join(format!(".{file_name}.{}.tmp", std::process::id()));

        let mut out = String::new();
        out.push_str(HEADER);
        out.push('\n');
        out.push('\n');
        for b in &self.bridges {
            out.push_str(&b.to_string());
            out.push('\n');
        }

        if !dir.as_os_str().is_empty() {
            fs::create_dir_all(dir).ok();
        }
        {
            let mut f =
                fs::File::create(&tmp).with_context(|| format!("create {}", tmp.display()))?;
            f.write_all(out.as_bytes())
                .with_context(|| format!("write {}", tmp.display()))?;
            f.sync_all()
                .with_context(|| format!("fsync {}", tmp.display()))?;
        }
        fs::rename(&tmp, &self.path)
            .with_context(|| format!("rename {} → {}", tmp.display(), self.path.display()))?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_dir() -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static SEQ: AtomicU64 = AtomicU64::new(0);
        let seq = SEQ.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!(
            "tor-socks5-candpool-test-{}-{}",
            std::process::id(),
            seq
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn b(line: &str) -> BridgeLine {
        line.parse().expect("test bridge parses")
    }

    const A: &str = "obfs4 1.2.3.4:80 ABCDEF0123456789ABCDEF0123456789ABCDEF01 cert=ZZZ iat-mode=0";
    const A_OTHER_PARAMS: &str =
        "obfs4 1.2.3.4:80 ABCDEF0123456789ABCDEF0123456789ABCDEF01 cert=YYY iat-mode=1";
    const B: &str =
        "obfs4 5.6.7.8:443 0123456789ABCDEF0123456789ABCDEF01234567 cert=WWW iat-mode=0";
    const WT: &str =
        "webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://e.com/x ver=0.0.3";

    fn empty(path: PathBuf) -> CandidatePool {
        CandidatePool {
            path,
            bridges: Vec::new(),
            keys: HashSet::new(),
        }
    }

    #[test]
    fn resolve_path_uses_stem() {
        let p = CandidatePool::resolve_path(Some(Path::new("/etc/tor-socks5.ktav")));
        assert_eq!(
            p.file_name().unwrap().to_string_lossy(),
            "tor-socks5.candidates.log"
        );
    }

    #[test]
    fn merge_dedups_and_excludes_working() {
        let mut p = empty(PathBuf::from("mem"));
        let working: HashSet<Key> = [key_of(&b(B))].into_iter().collect();
        // A and WT are new; B is excluded (already working); A_OTHER_PARAMS
        // is the same key as A → dedup.
        let added = p.merge(vec![b(A), b(B), b(WT), b(A_OTHER_PARAMS)], &working);
        assert_eq!(added, 2, "only A and WT are added");
        assert_eq!(p.len(), 2);
    }

    #[test]
    fn take_removes_from_front() {
        let mut p = empty(PathBuf::from("mem"));
        p.merge(vec![b(A), b(B), b(WT)], &HashSet::new());
        let taken = p.take(2);
        assert_eq!(taken.len(), 2);
        assert_eq!(p.len(), 1, "one left");
        // Re-merging a taken one succeeds (it was removed from keys).
        assert_eq!(p.merge(vec![b(A)], &HashSet::new()), 1);
    }

    #[test]
    fn save_load_roundtrip_dedups() {
        let dir = tmp_dir();
        let path = dir.join("c.log");
        let mut p = CandidatePool::load(path.clone()).unwrap();
        p.merge(vec![b(A), b(B), b(WT)], &HashSet::new());
        p.save().unwrap();

        let loaded = CandidatePool::load(path).unwrap();
        assert_eq!(loaded.len(), 3);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn missing_file_is_empty() {
        let dir = tmp_dir();
        let p = CandidatePool::load(dir.join("nope.log")).unwrap();
        assert!(p.is_empty());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn return_front_puts_back_unprobed() {
        let mut p = empty(PathBuf::from("mem"));
        p.merge(vec![b(B)], &HashSet::new());
        p.return_front(vec![b(A), b(WT)]);
        assert_eq!(p.len(), 3);
        // A and WT are at the front now.
        let taken = p.take(2);
        let keys: HashSet<Key> = taken.iter().map(key_of).collect();
        assert!(keys.contains(&key_of(&b(A))) && keys.contains(&key_of(&b(WT))));
    }
}
