//! Persistent pool of **unverified** bridge candidates.
//!
//! Fetching bridge lists (network → public collectors) is decoupled from
//! probing them (network → the bridges) and from using them (the working
//! config that arti bootstraps on):
//!
//! * a **refresh** fetches the source lists and merges the newcomers here,
//!   deduplicated and minus anything already in the working config;
//! * a **drain** walks this pool lazily (one bridge at a time), promotes
//!   the reachable ones into the working config, and removes every probed
//!   candidate from the pool (reachable → promoted, dead → discarded).
//!
//! Stored next to the active config as `<stem>.candidates.log`, a scratch
//! staging file (plain bridge lines, one per line):
//!
//! ```text
//! # Auto-generated by tor-socks5. Unverified bridge candidate pool.
//! obfs4 1.2.3.4:80 ABCDEF... cert=... iat-mode=0
//! webtunnel [2001:db8::1]:443 0123... url=https://example.com/x ver=0.0.3
//! ```
//!
//! Deduplication uses the canonical `BridgeIdentity` shared by all consumers.
//! The identity preserves the full WebTunnel carrier target and certificate.
//! Writers (refresh, drain) run their whole load→mutate→save cycle as one
//! cross-process transaction ([`CandidatePool::transaction`] or an explicitly
//! held [`crate::path_lock::PathLock`]): daemon maintenance and the
//! `bridges fetch` CLI serialize on the per-path lock instead of publishing
//! whole files over each other's snapshot.

use std::collections::HashSet;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use anyhow::{Context, Result};
use bridge_line::BridgeLine;
use bridge_probe::{bridge_identity, BridgeIdentity};

use crate::path_lock::{PathLock, POOL_LOCK_WAIT};

const HEADER: &str = "# Auto-generated by tor-socks5. Unverified bridge candidate pool.";
const DEFAULT_FILE: &str = "tor-socks5.candidates.log";
static SAVE_SEQ: AtomicU64 = AtomicU64::new(0);

fn cleanup_temp_files(path: &Path) {
    let Some(file_name) = path.file_name().map(|name| name.to_string_lossy()) else {
        return;
    };
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let prefix = format!(".{file_name}.");
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let stale = name.to_string_lossy().starts_with(&prefix)
            && name.to_string_lossy().ends_with(".tmp")
            && name
                .to_string_lossy()
                .strip_prefix(&prefix)
                .and_then(|rest| rest.split('.').next())
                .and_then(|pid| pid.parse::<u32>().ok())
                != Some(std::process::id());
        if stale {
            let _ = fs::remove_file(entry.path());
        }
    }
}

#[cfg(unix)]
fn sync_parent_dir(path: &Path) {
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let _ = fs::File::open(dir).and_then(|file| file.sync_all());
}

#[cfg(not(unix))]
fn sync_parent_dir(_path: &Path) {}

/// Dedup key shared with the config, fetcher and health store.
pub type Key = BridgeIdentity;

pub fn key_of(b: &BridgeLine) -> Key {
    bridge_identity(b)
}

#[derive(Debug)]
pub struct CandidatePool {
    path: PathBuf,
    /// Insertion-ordered candidates, deduplicated by [`key_of`].
    bridges: Vec<BridgeLine>,
    keys: HashSet<Key>,
}

impl CandidatePool {
    /// Pool transaction lock: held from the load through the save, so
    /// competing refresh/drain writers serialize instead of racing
    /// whole-file renames. The bounded wait runs on the blocking pool — a
    /// lock wait must never block an async worker.
    pub(crate) async fn acquire_transaction_lock(path: &Path) -> Result<PathLock> {
        let path = path.to_path_buf();
        tokio::task::spawn_blocking(move || {
            PathLock::acquire_bounded(&path, POOL_LOCK_WAIT)
                .with_context(|| format!("candidate pool transaction lock for {}", path.display()))
        })
        .await
        .map_err(|e| anyhow::anyhow!("candidate pool lock task failed: {e}"))?
    }

    /// One whole cross-process read-modify-write: transaction lock → load →
    /// mutate → save. What `f` removes stays removed — the published file is
    /// the freshly loaded pool mutated by `f`, never a union with a stale
    /// snapshot, so consumed/dead entries cannot be resurrected. Sync: the
    /// lock wait blocks; async flows holding the lock across awaits use
    /// [`CandidatePool::acquire_transaction_lock`] directly.
    pub fn transaction<T>(path: &Path, f: impl FnOnce(&mut CandidatePool) -> T) -> Result<T> {
        #[cfg(test)]
        crate::test_seams::park_if_armed(crate::test_seams::Site::PreAcquire, path);
        let _lock = PathLock::acquire_bounded(path, POOL_LOCK_WAIT)
            .with_context(|| format!("candidate pool transaction lock for {}", path.display()))?;
        let mut pool = CandidatePool::load(path.to_path_buf())?;
        #[cfg(test)]
        crate::test_seams::park_if_armed(crate::test_seams::Site::PostLoad, path);
        let out = f(&mut pool);
        pool.save()?;
        Ok(out)
    }

    /// Resolve the pool path from the config path: same dir + stem, fixed
    /// `.candidates.log` suffix (mirrors the alive-bridges log). Falls back
    /// to `./tor-socks5.candidates.log` for built-in defaults.
    pub fn resolve_path(config_path: Option<&Path>) -> PathBuf {
        match config_path {
            Some(cfg) => {
                let dir = cfg.parent().unwrap_or_else(|| Path::new("."));
                let stem = cfg
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_else(|| "tor-socks5".to_string());
                dir.join(format!("{stem}.candidates.log"))
            }
            None => PathBuf::from(DEFAULT_FILE),
        }
    }

    /// Load the pool, ignoring malformed/duplicate lines. Missing file →
    /// empty pool.
    pub fn load(path: PathBuf) -> Result<Self> {
        cleanup_temp_files(&path);
        let mut pool = Self {
            path,
            bridges: Vec::new(),
            keys: HashSet::new(),
        };
        let text = match fs::read_to_string(&pool.path) {
            Ok(s) => s,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(pool),
            Err(e) => return Err(e).with_context(|| format!("read {}", pool.path.display())),
        };
        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Ok(bridge) = line.parse::<BridgeLine>() {
                pool.push_unique(bridge);
            }
        }
        Ok(pool)
    }

    fn push_unique(&mut self, bridge: BridgeLine) -> bool {
        let key = key_of(&bridge);
        if self.keys.insert(key) {
            self.bridges.push(bridge);
            true
        } else {
            false
        }
    }

    /// Merge fetched candidates, skipping any already present in the pool
    /// or whose key is in `exclude` (the working set). Returns how many
    /// were newly added.
    pub fn merge(
        &mut self,
        fetched: impl IntoIterator<Item = BridgeLine>,
        exclude: &HashSet<Key>,
    ) -> usize {
        let mut added = 0;
        for bridge in fetched {
            if exclude.contains(&key_of(&bridge)) {
                continue;
            }
            if self.push_unique(bridge) {
                added += 1;
            }
        }
        added
    }

    /// Remove and return up to `n` candidates from the front of the pool.
    pub fn take(&mut self, n: usize) -> Vec<BridgeLine> {
        let n = n.min(self.bridges.len());
        let taken: Vec<BridgeLine> = self.bridges.drain(..n).collect();
        for b in &taken {
            self.keys.remove(&key_of(b));
        }
        taken
    }

    /// Select across the whole pool; other transports keep their queue positions.
    pub fn take_transport(&mut self, n: usize, transport: Option<&str>) -> Vec<BridgeLine> {
        let Some(transport) = transport else {
            return self.take(n);
        };
        if n == 0 || self.bridges.is_empty() {
            return Vec::new();
        }
        // One pass: move out the first `n` matches; the scan stops as soon
        // as the batch is complete and the rest keeps its relative order.
        let mut taken = Vec::new();
        let mut kept = Vec::with_capacity(self.bridges.len().saturating_sub(n));
        let mut rest = std::mem::take(&mut self.bridges).into_iter();
        for bridge in rest.by_ref() {
            if bridge.transport.as_deref() == Some(transport) {
                taken.push(bridge);
                if taken.len() == n {
                    break;
                }
            } else {
                kept.push(bridge);
            }
        }
        kept.extend(rest);
        self.bridges = kept;
        for bridge in &taken {
            self.keys.remove(&key_of(bridge));
        }
        taken
    }

    pub fn prioritize(&mut self, fresh: &[BridgeLine], transport: Option<&str>) {
        // The full dedup key ([`key_of`]) must match merge/exclude: a
        // shortened key would mark a stale variant of a relay as fresh
        // alongside the actual tested-list entry. Keys for `fresh` are built
        // once up front; sort_by_cached_key computes each pool key once and
        // keeps the sort stable.
        let fresh_keys: HashSet<Key> = fresh
            .iter()
            .filter(|bridge| transport.is_none_or(|name| bridge.transport.as_deref() == Some(name)))
            .map(key_of)
            .collect();
        self.bridges
            .sort_by_cached_key(|bridge| !fresh_keys.contains(&key_of(bridge)));
    }

    /// Put bridges back at the front of the pool (e.g. a taken batch that
    /// was not probed this round), preserving dedup.
    pub fn return_front(&mut self, bridges: Vec<BridgeLine>) {
        let mut prefix = Vec::with_capacity(bridges.len());
        for b in bridges {
            if self.keys.insert(key_of(&b)) {
                prefix.push(b);
            }
        }
        prefix.append(&mut self.bridges);
        self.bridges = prefix;
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.bridges.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.bridges.is_empty()
    }

    /// Atomic write via sibling temp file + rename.
    pub fn save(&self) -> Result<()> {
        let dir = self.path.parent().unwrap_or_else(|| Path::new("."));
        let file_name = self
            .path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| DEFAULT_FILE.to_string());
        let seq = SAVE_SEQ.fetch_add(1, Ordering::Relaxed);
        let tmp = dir.join(format!(".{file_name}.{}.{seq}.tmp", std::process::id()));

        let mut out = String::new();
        out.push_str(HEADER);
        out.push('\n');
        out.push('\n');
        for b in &self.bridges {
            out.push_str(&b.to_string());
            out.push('\n');
        }

        if !dir.as_os_str().is_empty() {
            fs::create_dir_all(dir).ok();
        }
        {
            let mut f =
                fs::File::create(&tmp).with_context(|| format!("create {}", tmp.display()))?;
            f.write_all(out.as_bytes())
                .with_context(|| format!("write {}", tmp.display()))?;
            f.sync_all()
                .with_context(|| format!("fsync {}", tmp.display()))?;
        }
        match fs::rename(&tmp, &self.path)
            .with_context(|| format!("rename {} → {}", tmp.display(), self.path.display()))
        {
            Ok(()) => {
                sync_parent_dir(&self.path);
                Ok(())
            }
            Err(error) => {
                let _ = fs::remove_file(&tmp);
                Err(error)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_seams::{HANG_GUARD, UNBLOCK_GUARD};

    fn tmp_dir() -> PathBuf {
        use std::sync::atomic::{AtomicU64, Ordering};
        static SEQ: AtomicU64 = AtomicU64::new(0);
        let seq = SEQ.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!(
            "tor-socks5-candpool-test-{}-{}",
            std::process::id(),
            seq
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn b(line: &str) -> BridgeLine {
        line.parse().expect("test bridge parses")
    }

    const A: &str = "obfs4 1.2.3.4:80 ABCDEF0123456789ABCDEF0123456789ABCDEF01 cert=ZZZ iat-mode=0";
    const A_OTHER_PARAMS: &str =
        "obfs4 1.2.3.4:80 ABCDEF0123456789ABCDEF0123456789ABCDEF01 cert=YYY iat-mode=1";
    const B: &str =
        "obfs4 5.6.7.8:443 0123456789ABCDEF0123456789ABCDEF01234567 cert=WWW iat-mode=0";
    const WT: &str =
        "webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://e.com/x ver=0.0.3";

    const WT_NEW: &str =
        "webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://e.com/new ver=0.0.3";

    fn empty(path: PathBuf) -> CandidatePool {
        CandidatePool {
            path,
            bridges: Vec::new(),
            keys: HashSet::new(),
        }
    }

    #[test]
    fn resolve_path_uses_stem() {
        let p = CandidatePool::resolve_path(Some(Path::new("/etc/tor-socks5.ktav")));
        assert_eq!(
            p.file_name().unwrap().to_string_lossy(),
            "tor-socks5.candidates.log"
        );
    }

    #[test]
    fn load_removes_own_stale_temp_files() {
        let dir = tmp_dir();
        let path = dir.join("candidates.log");
        let stale = dir.join(".candidates.log.1.42.tmp");
        fs::write(&stale, "partial").unwrap();
        CandidatePool::load(path).expect("load");
        assert!(!stale.exists());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn merge_dedups_and_excludes_working() {
        let mut p = empty(PathBuf::from("mem"));
        let working: HashSet<Key> = [key_of(&b(B))].into_iter().collect();
        // A, WT and A_OTHER_PARAMS are new: A_OTHER_PARAMS carries a different
        // obfs4 cert, so it is a distinct endpoint, not a duplicate of A. B is
        // excluded (already working, same cert).
        let added = p.merge(vec![b(A), b(B), b(WT), b(A_OTHER_PARAMS)], &working);
        assert_eq!(added, 3, "only B is excluded");
        assert_eq!(p.len(), 3);
    }

    #[test]
    fn merge_keeps_fresh_cert_when_stale_cert_is_already_pooled() {
        // The server rotated its obfs4 key: same relay, new cert. The fresh
        // line must be pooled alongside the stale one instead of being
        // dropped as a "duplicate".
        let mut p = empty(PathBuf::from("mem"));
        assert_eq!(p.merge([b(A)], &HashSet::new()), 1);
        let added = p.merge([b(A_OTHER_PARAMS)], &HashSet::new());
        assert_eq!(added, 1, "fresh cert on the same relay must not be dropped");
        assert_eq!(p.len(), 2);
        // An exact duplicate (same cert) still dedups.
        assert_eq!(p.merge([b(A)], &HashSet::new()), 0);
        assert_eq!(p.len(), 2);
    }

    #[test]
    fn working_set_with_stale_cert_does_not_exclude_fresh_cert() {
        // Mirror of fetch_merge::working_keys: the exclude set is built with
        // key_of, so a working line with the old cert must not swallow a
        // fresh-cert candidate from a source.
        let working: HashSet<Key> = [key_of(&b(A))].into_iter().collect();
        assert!(!working.contains(&key_of(&b(A_OTHER_PARAMS))));
        let mut p = empty(PathBuf::from("mem"));
        assert_eq!(p.merge([b(A_OTHER_PARAMS)], &working), 1);
    }

    #[test]
    fn take_removes_from_front() {
        let mut p = empty(PathBuf::from("mem"));
        p.merge(vec![b(A), b(B), b(WT)], &HashSet::new());
        let taken = p.take(2);
        assert_eq!(taken.len(), 2);
        assert_eq!(p.len(), 1, "one left");
        // Re-merging a taken one succeeds (it was removed from keys).
        assert_eq!(p.merge(vec![b(A)], &HashSet::new()), 1);
    }

    #[test]
    fn preferred_transport_is_found_beyond_the_front_batch() {
        let mut pool = empty(PathBuf::from("mem"));
        let obfs: Vec<_> = (1..=100)
            .map(|i| {
                b(&format!(
                    "obfs4 1.2.3.{i}:443 ABCDEF0123456789ABCDEF0123456789ABCDEF01 cert=AAA"
                ))
            })
            .collect();
        pool.merge(obfs.clone(), &HashSet::new());
        pool.merge([b(WT)], &HashSet::new());
        assert_eq!(pool.take_transport(1, Some("webtunnel")), vec![b(WT)]);
        assert_eq!(pool.take(100), obfs, "fallback candidates must stay queued");
    }

    #[test]
    fn zero_batch_takes_nothing_even_with_transport_filter() {
        let mut pool = empty(PathBuf::from("mem"));
        pool.merge([b(WT), b(A)], &HashSet::new());
        assert!(pool.take_transport(0, Some("webtunnel")).is_empty());
        assert!(pool.take_transport(0, None).is_empty());
        assert_eq!(pool.len(), 2, "zero-size batch must leave the pool intact");
        let mut pool = empty(PathBuf::from("mem"));
        assert!(pool.take_transport(3, Some("webtunnel")).is_empty());
        assert!(pool.take_transport(3, None).is_empty());
    }

    #[test]
    fn a_migrated_tested_list_moves_a_cached_candidate_to_the_front() {
        let mut pool = empty(PathBuf::from("mem"));
        let wt = b(WT);
        let mut old = wt.clone();
        old.fingerprint = Some("2222222222222222222222222222222222222222".into());
        pool.merge([b(A), old.clone(), wt.clone()], &HashSet::new());
        pool.prioritize(std::slice::from_ref(&wt), Some("webtunnel"));
        assert_eq!(pool.take_transport(1, Some("webtunnel")), vec![wt]);
        assert_eq!(pool.take_transport(1, Some("webtunnel")), vec![old]);
        assert_eq!(pool.take(1), vec![b(A)]);
    }

    #[test]
    fn save_load_roundtrip_dedups() {
        let dir = tmp_dir();
        let path = dir.join("c.log");
        let mut p = CandidatePool::load(path.clone()).unwrap();
        p.merge(vec![b(A), b(B), b(WT)], &HashSet::new());
        p.save().unwrap();

        let loaded = CandidatePool::load(path).unwrap();
        assert_eq!(loaded.len(), 3);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn missing_file_is_empty() {
        let dir = tmp_dir();
        let p = CandidatePool::load(dir.join("nope.log")).unwrap();
        assert!(p.is_empty());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn merge_adds_webtunnel_with_new_url_on_same_relay() {
        let mut p = empty(PathBuf::from("mem"));
        p.merge([b(WT)], &HashSet::new());
        let added = p.merge([b(WT_NEW)], &HashSet::new());
        assert_eq!(added, 1, "new url on the same relay must not be dropped");
        assert_eq!(p.len(), 2);
        assert_eq!(p.merge([b(WT_NEW)], &HashSet::new()), 0);
        assert_eq!(p.len(), 2);
    }

    #[test]
    fn merge_keeps_webtunnel_servername_variants_distinct() {
        let mut p = empty(PathBuf::from("mem"));
        let added = p.merge(
            [
                b("webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://edge.example/x servername=old.example ver=0.0.3"),
                b("webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://edge.example/x servername=new.example ver=0.0.3"),
            ],
            &HashSet::new(),
        );
        assert_eq!(
            added, 2,
            "different servername= must stay distinct candidates"
        );
        let again = p.merge(
            [b("webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://edge.example/x servername=old.example ver=0.0.3")],
            &HashSet::new(),
        );
        assert_eq!(again, 0);
    }

    #[test]
    fn merge_keeps_plain_http_and_tls_variants_distinct() {
        let mut p = empty(PathBuf::from("mem"));
        let added = p.merge(
            [
                b("webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=http://edge.example:443/x ver=0.0.3"),
                b("webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://edge.example/x ver=0.0.3"),
            ],
            &HashSet::new(),
        );
        assert_eq!(
            added, 2,
            "plain HTTP vs TLS on one dial address must stay distinct"
        );
    }

    #[test]
    fn merge_keeps_virtual_hosts_on_one_addr_distinct() {
        let mut p = empty(PathBuf::from("mem"));
        let added = p.merge(
            [
                b("webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://a.example/x addr=9.9.9.9:443 ver=0.0.3"),
                b("webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://b.example/x addr=9.9.9.9:443 ver=0.0.3"),
            ],
            &HashSet::new(),
        );
        assert_eq!(
            added, 2,
            "distinct virtual hosts behind one addr= must stay distinct"
        );
    }

    #[test]
    fn merge_dedups_literally_identical_webtunnel_configs() {
        let line = "webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 \
url=https://edge.example/x servername=edge.example addr=9.9.9.9:443 ver=0.0.3";
        let mut p = empty(PathBuf::from("mem"));
        assert_eq!(p.merge([b(line)], &HashSet::new()), 1);
        assert_eq!(
            p.merge([b(line)], &HashSet::new()),
            0,
            "identical url/servername/addr dedups to one"
        );
        assert_eq!(p.len(), 1);
    }

    #[test]
    fn prioritized_fresh_variant_bumps_only_its_own_identity() {
        // A stale variant of the same relay (/old) must not be ranked fresh
        // by a migrated tested list that only carries the new one (/new).
        let wt_old = b(
            "webtunnel 9.9.9.9:443 1111111111111111111111111111111111111111 url=https://e.com/old ver=0.0.3",
        );
        let wt_new = b(WT_NEW);
        let mut pool = empty(PathBuf::from("mem"));
        pool.merge([wt_old.clone(), wt_new.clone()], &HashSet::new());
        pool.prioritize([wt_new.clone()].as_slice(), Some("webtunnel"));
        assert_eq!(
            pool.take(1),
            vec![wt_new],
            "the fresh variant must come before the stale one of the same relay"
        );
        assert_eq!(pool.take(1), vec![wt_old]);
    }

    #[test]
    fn prioritize_distinguishes_carrier_identity_differences() {
        let fp = |n: u8| format!("{:038x}{:02x}", 0x1111, n);
        let urls = ["https://e.com/x", "https://f.com/x", "https://g.com/x"];
        // Stale variants differing only in servername / TLS-vs-plain / addr=.
        let stale = [
            b(&format!(
                "webtunnel 9.9.9.9:443 {} url={}/o servername=old.example ver=0.0.3",
                fp(1),
                urls[0]
            )),
            b(&format!(
                "webtunnel 9.9.9.9:443 {} url=http://f.com:443/x ver=0.0.3",
                fp(2)
            )),
            b(&format!(
                "webtunnel 9.9.9.9:443 {} url={}/o addr=8.8.8.8:443 ver=0.0.3",
                fp(3),
                urls[2]
            )),
        ];
        let fresh = [
            b(&format!(
                "webtunnel 9.9.9.9:443 {} url={}/x servername=new.example ver=0.0.3",
                fp(1),
                urls[0]
            )),
            b(&format!(
                "webtunnel 9.9.9.9:443 {} url=https://f.com/x ver=0.0.3",
                fp(2)
            )),
            b(&format!(
                "webtunnel 9.9.9.9:443 {} url={}/x addr=9.9.9.9:443 ver=0.0.3",
                fp(3),
                urls[2]
            )),
        ];
        let mut pool = empty(PathBuf::from("mem"));
        // Interleave stale and fresh so only correct keying yields the
        // fresh ones first.
        let mut all = Vec::new();
        for i in 0..3 {
            all.push(stale[i].clone());
            all.push(fresh[i].clone());
        }
        pool.merge(all, &HashSet::new());
        pool.prioritize(fresh.as_slice(), Some("webtunnel"));
        let taken = pool.take(3);
        for (i, fresh_bridge) in fresh.iter().enumerate() {
            assert_eq!(
                key_of(&taken[i]),
                key_of(fresh_bridge),
                "each fresh variant must outrank its stale twin (case {i})"
            );
        }
    }

    #[test]
    fn prioritize_keeps_stable_order_for_equivalent_carriers() {
        let mut pool = empty(PathBuf::from("mem"));
        let order = [b(A), b(B), b(WT)];
        pool.merge(order.clone(), &HashSet::new());
        // Nothing in `fresh` matches; relative order must be unchanged.
        pool.prioritize([b(WT_NEW)].as_slice(), Some("webtunnel"));
        assert_eq!(pool.take(3), order);
        // Same for an empty fresh list with no transport filter.
        pool.merge(order.clone(), &HashSet::new());
        pool.prioritize(&[], None);
        assert_eq!(pool.take(3), order);
    }

    #[test]
    fn return_front_puts_back_unprobed() {
        let mut p = empty(PathBuf::from("mem"));
        p.merge(vec![b(B)], &HashSet::new());
        p.return_front(vec![b(A), b(WT)]);
        assert_eq!(p.len(), 3);
        // A and WT are at the front now.
        let taken = p.take(2);
        let keys: HashSet<Key> = taken.iter().map(key_of).collect();
        assert!(keys.contains(&key_of(&b(A))) && keys.contains(&key_of(&b(WT))));
    }

    /// Two competing transactions serialize on the pool lock: both mutations
    /// land, and a consumed entry stays consumed (no blind union).
    /// Forcing: T2 is parked before its acquisition and released only while
    /// T1 provably owns the lock (parked after its load, unreleased). T1's
    /// gate is released after T2 completes, or — when T2 is correctly still
    /// blocked — after a guard timeout; the timeout only picks the releaser,
    /// the lock itself orders the correct-mode outcome.
    #[test]
    fn competing_transactions_serialize_and_removals_stay_removed() {
        let dir = tmp_dir();
        let path = dir.join("c.log");
        let mut seed = CandidatePool::load(path.clone()).unwrap();
        assert_eq!(seed.merge(vec![b(A), b(B)], &HashSet::new()), 2);
        seed.save().unwrap();

        let pre = crate::test_seams::ParkedGate::arm(crate::test_seams::Site::PreAcquire, &path);
        let post = crate::test_seams::ParkedGate::arm(crate::test_seams::Site::PostLoad, &path);
        let post_for_t2 = post.clone();
        let (t2_done_tx, t2_done_rx) = std::sync::mpsc::channel();
        let t2_path = path.clone();
        let t2 = std::thread::spawn(move || {
            let out = CandidatePool::transaction(&t2_path, |p| p.take(1));
            post_for_t2.release();
            let _ = t2_done_tx.send(());
            out
        });
        pre.wait_parked(HANG_GUARD);

        let t1_path = path.clone();
        let t1 = std::thread::spawn(move || {
            CandidatePool::transaction(&t1_path, |p| p.merge([b(WT)], &HashSet::new()))
        });
        post.wait_parked(HANG_GUARD);

        // T2 now reaches its acquisition while T1 owns the lock.
        pre.release();
        let _t2_finished = t2_done_rx.recv_timeout(UNBLOCK_GUARD).is_ok();
        // In the locked case T2 is still waiting; in the lock-bypass
        // negative control it already saved. Release T1 in either case so
        // the final state assertions report the bypass instead of hanging.
        post.release();

        let added = t1.join().unwrap().unwrap();
        let taken = t2.join().unwrap().unwrap();
        assert_eq!(added, 1, "T1 adds WT");
        assert_eq!(taken, vec![b(A)], "T2 removes the front entry, A");

        let mut final_pool = CandidatePool::load(path).unwrap();
        assert_eq!(
            final_pool.take(10),
            vec![b(B), b(WT)],
            "the competing addition must survive and the consumed A must stay removed"
        );
        let _ = fs::remove_dir_all(&dir);
    }
}
